return {
  room_loot={ { x=-1.5, z=-3.5,},},
  spawner_creature={
    { script_args={ creature_spawner_type="perimeter",}, x=22.92, z=-27.62,},
    { script_args={ creature_spawner_type="perimeter",}, x=39.21, z=13.88,},
    { script_args={ creature_spawner_type="perimeter",}, x=-25.42, z=-26.92,},
    { script_args={ creature_spawner_type="perimeter",}, x=39.42, z=6.03,},
    { script_args={ creature_spawner_type="battlefield",}, x=7.25, z=10.54,},
    { script_args={ creature_spawner_type="battlefield",}, x=-9.99, z=-2.8,},
    { script_args={ creature_spawner_type="battlefield",}, x=20.64, z=-1.8,},
    { script_args={ creature_spawner_type="battlefield",}, x=-23.96, z=-11.64,},
    { script_args={ creature_spawner_type="battlefield",}, x=-22.88, z=-10.88,},
    { script_args={ creature_spawner_type="battlefield",}, x=-22.46, z=9.25,},
    { script_args={ creature_spawner_type="battlefield",}, x=-1.93, z=-10.55,},
    { script_args={ creature_spawner_type="battlefield",}, x=21.74, z=-0.19,},
    { script_args={ creature_spawner_type="perimeter",}, x=-42.82, z=13.63,},
    { script_args={ creature_spawner_type="battlefield",}, x=-9.13, z=-3.95,},
    { script_args={ creature_spawner_type="perimeter",}, x=-43.18, z=-14.85,},
    { script_args={ creature_spawner_type="battlefield",}, x=14.81, z=7.81,},
    { script_args={ creature_spawner_type="battlefield",}, x=23.99, z=-11.88,},
  },
  spawner_propdestructible={
    { z=29.0,},
    { x=-18, z=-13,},
    { x=-1.0, z=-17,},
    { x=8.0, z=16.0,},
    { x=-16, z=10,},
    { x=18, z=-9,},
    { x=21, z=11,},
    { x=27, z=5,},
    { x=12, z=-11,},
    { x=-8, z=12,},
  },
  spawner_trap={
    { script_args={ trap_types={ "trap_cold",},}, x=9.5, z=3.5,},
    { script_args={ trap_types={ "trap_torch",},}, x=-21.5, z=-6.5,},
    { script_args={ trap_types={ "trap_torch",},}, x=-6.5, z=2.5,},
    { script_args={ trap_types={ "trap_torch",},}, x=14.5, z=-2.5,},
  },
}