-- Generated by CurveEditor and loaded by curve_autogen.lua
return {
  __displayName="example_trap_spike_bloom_off",
  curve={
    0.0,
    1.0,
    0.21666666865349,
    0.50999999046326,
    0.56666666269302,
    0.69499999284744,
    0.75,
    0.25499999523163,
    1.0,
    0.0,
    -1.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
  },
  group="example",
}
