-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_nose_color_9",
  cosmetic_data={
    color={ 0.086274512112141, 0.0, 0.36293435096741,},
    color_species="canine",
    colorgroup="NOSE_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  locked=false,
}
