-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_ear_color_5",
  cosmetic_data={
    color={ 0.057915057986975, 0.47876447439194, 0.58687257766724,},
    colorgroup="EAR_COLOR",
    color_species="canine",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  
  locked=false,
  
  
  
  
}
