-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_midnight_hair_color_1",
  cosmetic_data={
    color={ 0.66666666666667, 0.2, 0.32,},
    colorgroup="HAIR_COLOR",
    color_species="canine",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  
  locked=false,
  
  
  
  
}
