-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_terrarosa_hair_color_1",
  cosmetic_data={
    color={ 0.98611111111111, 0.35, 0.6,},
    color_species="canine",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
