-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_undies_color_3",
  cosmetic_data={
    color={ 0.027777777777778, 0.35, 0.6,},
    colorgroup="UNDIES_COLOR",
    color_species="canine",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  
  locked=false,
  
  
  
  
}
