-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_tangerine_skin_tone_1",
  cosmetic_data={
    color={ 0.054901961237192, 0.78764480352402, 0.94208496809006,},
    color_species="canine",
    colorgroup="SKIN_TONE",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
