-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_red_eye_color_1",
  cosmetic_data={
    color={ 0.0027777777777778, 0.5, 1.0,},
    colorgroup="EYE_COLOR",
    color_species="canine",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  
  locked=false,
  
  
  
  
}
