-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_brown_hair_color_1",
  cosmetic_data={
    color={ 0.058333333333333, 0.7, 0.47,},
    colorgroup="HAIR_COLOR",
    color_species="canine",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  
  locked=false,
  
  
  
  
}
