-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_flax_skin_tone_1",
  cosmetic_data={
    color={ 0.13055555522442, 0.30888029932976, 0.97683399915695,},
    color_species="canine",
    colorgroup="SKIN_TONE",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
