-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="canine_mouth_color_1",
  cosmetic_data={
    color={ 0.91388888888889, 0.39, 0.95,},
    color_species="canine",
    colorgroup="MOUTH_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  locked=false,
}
