-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="default_title",
  cosmetic_data={ title_key="DEFAULT_TITLE",},
  group="PLAYER_TITLE",
  
  locked=false,
  
  
    
}
