-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="emote_shoulder_look",
  cosmetic_data={
    anim="emote_shoulder_look",
    emote_species="none",
    icon_path="images/icons_ftf/item_temp.tex",
    name_key="emote_shoulder_look",
  },
  group="PLAYER_EMOTE",
  
  locked=false,
  
  
  
}
