-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="forestkeeper",
  cosmetic_data={ title_key="FORESTKEEPER",},
  group="PLAYER_TITLE",
  
  locked=true,
  
  
  
  
}
