-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="madtrickster",
  cosmetic_data={ title_key="MADTRICKSTER",},
  group="PLAYER_TITLE",
  
  locked=true,
  
  
  
  
}
