-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_plump_eyes",
  cosmetic_data={
    bodypart_group="EYES",
    bodypart_species="mer",
    build="player_eyes_mer_plump",
    colorgroup="EYE_COLOR",
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  locked=true,
}
