-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_neonyellow_ornament_color_1",
  cosmetic_data={
    color={ 0.15277777612209, 0.40926641225815, 1.0,},
    color_species="mer",
    colorgroup="ORNAMENT_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
