-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_dustyblue_hair_color_1",
  cosmetic_data={
    color={ 0.62548261880875, 0.61003863811493, 0.55212354660034,},
    color_species="mer",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
