-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_purple_ornament_color_2",
  cosmetic_data={
    color={ 0.69884169101715, 0.96138995885849, 0.55598455667496,},
    color_species="mer",
    colorgroup="ORNAMENT_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  locked=false,
}
