-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_neonblue_ornament_color_1",
  cosmetic_data={
    color={ 0.50965249538422, 0.38223937153816, 0.97297298908234,},
    color_species="mer",
    colorgroup="ORNAMENT_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
