-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_neongreen_ornament_color_1",
  cosmetic_data={
    color={ 0.38333332538605, 0.27799227833748, 0.97683399915695,},
    color_species="mer",
    colorgroup="ORNAMENT_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
