-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_orange_ornament_color_1",
  cosmetic_data={
    color={ 0.047222223132849, 0.95366793870926, 0.70270270109177,},
    color_species="mer",
    colorgroup="ORNAMENT_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
