-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_black_ornament_color_1",
  cosmetic_data={
    color={ 0.73888885974884, 0.31660231947899, 0.24324321746826,},
    color_species="mer",
    colorgroup="ORNAMENT_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
