-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_alizarin_hair_color_1",
  cosmetic_data={
    color={ 0.94444444444444, 0.65, 0.53,},
    color_species="mer",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
