-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_scaley_hair_back",
  cosmetic_data={
    bodypart_group="HAIR_BACK",
    bodypart_species="mer",
    build="player_hair_mer_scaley",
    colorgroup="HAIR_COLOR",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  locked=false,
}
