-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_neonpink_ornament_color_1",
  cosmetic_data={
    color={ 0.80555555555556, 0.33, 1.0,},
    color_species="mer",
    colorgroup="ORNAMENT_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
