-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_cute_mouth",
  cosmetic_data={
    bodypart_group="MOUTH",
    bodypart_species="mer",
    build="player_mouth_mer_cute",
    colorgroup="MOUTH_COLOR",
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  locked=true,
}
