-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_fang_mouth_1",
  cosmetic_data={
    bodypart_group="MOUTH",
    bodypart_species="mer",
    build="player_mouth_mer_fang",
    colorgroup="NONE",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  locked=false,
}
