-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_viridian_hair_color_1",
  cosmetic_data={
    color={ 0.50277775526047, 0.57142859697342, 0.47104245424271,},
    color_species="mer",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
