-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_ultramarine_hair_color_1",
  cosmetic_data={
    color={ 0.64092665910721, 0.72972971200943, 0.36679536104202,},
    color_species="mer",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
