-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_ochre_hair_color_1",
  cosmetic_data={
    color={ 0.11388888888889, 0.51, 0.86,},
    color_species="mer",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
