-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_azul_skin_tone_1",
  cosmetic_data={
    color={ 0.63320463895798, 0.6138995885849, 0.62934362888336,},
    color_species="mer",
    colorgroup="SKIN_TONE",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
