-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_dustyblue_skin_tone_1",
  cosmetic_data={
    color={ 0.61776059865952, 0.42471042275429, 0.83397686481476,},
    color_species="mer",
    colorgroup="SKIN_TONE",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
