-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_curved_nose_1",
  cosmetic_data={
    bodypart_group="NOSE",
    bodypart_species="mer",
    build="player_nose_mer_curved",
    colorgroup="SKIN_TONE",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  locked=false,
}
