-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="mer_small_nose",
  cosmetic_data={
    bodypart_group="NOSE",
    bodypart_species="mer",
    build="player_nose_mer_small",
    colorgroup="NOSE_COLOR",
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  locked=true,
}
