-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="nightshroud",
  cosmetic_data={ title_key="NIGHTSHROUD",},
  group="PLAYER_TITLE",
  
  locked=true,
  
  
  
  
}
