-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="none_brow_canine_1",
  cosmetic_data={
    bodypart_group="BROW",
    bodypart_species="canine",
    multi_species=true,
    symboltags={  },
    uitags={ "blank",},
  },
  group="PLAYER_BODYPART",
  
  locked=false,
  
  
  
  
}
