-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_undies_color_2",
  cosmetic_data={
    color={ 0.69444444444444, 0.35, 0.6,},
    colorgroup="UNDIES_COLOR",
    color_species="ogre",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  
  locked=false,
  
  
  
  
}
