-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_nose_color_5",
  cosmetic_data={
    color={ 0.41698840260506, 0.40926641225815, 0.5675675868988,},
    color_species="ogre",
    colorgroup="NOSE_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  locked=false,
}
