-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_green_hair_color_1",
  cosmetic_data={
    color={ 0.3552123606205, 0.43629342317581, 0.83783781528473,},
    color_species="ogre",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
