-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_nose_color_1",
  cosmetic_data={
    color={ 0.91388887166977, 0.42084941267967, 0.94594591856003,},
    color_species="ogre",
    colorgroup="NOSE_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  locked=false,
}
