-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_ear_color_5",
  cosmetic_data={
    color={ 0.41568627953529, 0.40784314274788, 0.5686274766922,},
    color_species="ogre",
    colorgroup="EAR_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  locked=false,
}
