-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_nose_color_3",
  cosmetic_data={
    color={ 0.015686275437474, 0.73333334922791, 0.54509806632996,},
    color_species="ogre",
    colorgroup="NOSE_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  locked=false,
}
