-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_red_eye_color_1",
  cosmetic_data={
    color={ 0.0039215688593686, 0.4285714328289, 0.88803088665009,},
    color_species="ogre",
    colorgroup="EYE_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  locked=false,
}
