-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_copper_skin_tone_1",
  cosmetic_data={
    color={ 0.073359072208405, 0.68339771032333, 0.65250968933105,},
    color_species="ogre",
    colorgroup="SKIN_TONE",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
