-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_ear_color_2",
  cosmetic_data={
    color={ 0.023529412224889, 0.41176471114159, 0.58039218187332,},
    color_species="ogre",
    colorgroup="EAR_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  locked=false,
}
