-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_brown_hair_color_1",
  cosmetic_data={
    color={ 0.030555555596948, 0.42084941267967, 0.66409265995026,},
    color_species="ogre",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
