-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_ear_color_1",
  cosmetic_data={
    color={ 0.91372549533844, 0.419607847929, 0.9450980424881,},
    color_species="ogre",
    colorgroup="EAR_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  locked=false,
}
