-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_nose_color_7",
  cosmetic_data={
    color={ 0.75289577245712, 0.54826253652573, 0.58301162719727,},
    color_species="ogre",
    colorgroup="NOSE_COLOR",
    multi_species=true,
  },
  group="PLAYER_COLOR",
  locked=false,
}
