-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_midnight_hair_color_1",
  cosmetic_data={
    color={ 0.74903476238251, 0.56000000238419, 0.23999999463558,},
    color_species="ogre",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
