-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_strawberryblonde_hair_color_1",
  cosmetic_data={
    color={ 0.11196911334991, 0.45173746347427, 0.99613898992538,},
    color_species="ogre",
    colorgroup="HAIR_COLOR",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  locked=false,
}
