-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="ogre_darkbrown_hair_color_1",
  cosmetic_data={
    color={ 0.025, 0.35, 0.33,},
    colorgroup="HAIR_COLOR",
    color_species="ogre",
    multi_species=false,
  },
  group="PLAYER_COLOR",
  
  locked=false,
  
  
  
  
}
