-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="smear_weapon_color_canine_1",
  cosmetic_data={ color={ 0.5, 0.5, 1.0,}, colorgroup="SMEAR_WEAPON_COLOR", color_species="canine",},
  group="PLAYER_COLOR",
  locked=false,
}
