-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="smear_weapon_ogre_1",
  cosmetic_data={
    bodypart_group="SMEAR_WEAPON",
    build="fx_player_weapon_smear",
    colorgroup="SMEAR_WEAPON_COLOR",
    bodypart_species="ogre",
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  locked=false,
}
