-- Generated by CosmeticEditor and loaded by cosmetic_autogen.lua
return {
  __displayName="smear_canine_1",
  cosmetic_data={
    bodypart_group="SMEAR",
    bodypart_species="canine",
    build="fx_player_smear",
    colorgroup="SKIN_TONE",
    multi_species=false,
    symboltags={  },
    uitags={  },
  },
  group="PLAYER_BODYPART",
  locked=false,
}
