-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="armory",
  bank="armory",
  build="armory",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="town_decor",
  hostspawn=true,
  networked=1,
  parallax={ { anim="1", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  physicssize=1.5,
  physicstype="smdec",
  script="screenopener",
  script_args={ screen_require="screens.town.armoryscreen",},
  sound=true,
}
