-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_bg_bug",
  bank="bandiforest_bg_deadbug",
  build="bandiforest_bg_deadbug",
  fade={ bottom=-3.88, top=1.24,},
  group="swamp_props",
  layer="auto",
  parallax={
    { anim="bug_above", autosortlayer="above",},
    {
      anim="bug_below",
      autosortlayer="below",
      dist=9.9999997473788e-05,
      underground=true,
    },
  },
  proptype=1,
  variations=3,
}
