-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_grid_reedblue",
  bank="bandiforest_grid_reed",
  brightness=0,
  build="bandiforest_grid_reed",
  group="swamp_props",
  hue=0,
  looping=true,
  parallax={
    { anim="bluefront", dist=-0.3, shadow=true,},
    { anim="bluemid", shadow=true,},
    { anim="blueback", dist=0.5, shadow=true,},
  },
  randomstartframe=true,
  saturation=0,
}
