-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_bg_lilypad_cut",
  bank="bandiforest_bg_lilypad",
  build="bandiforest_bg_lilypad",
  fade={ bottom=-3.7, top=0.53,},
  group="swamp_props",
  hue=-17.0,
  layer="auto",
  parallax={
    { anim="frontcut_above", autosortlayer="above", dist=-0.5,},
    { anim="midcut_above", autosortlayer="above",},
    { anim="backcut_above", autosortlayer="above", dist=0.5,},
    {
      anim="frontcut_below",
      autosortlayer="below",
      dist=-0.50010001659393,
      underground=true,
    },
    {
      anim="midcut_below",
      autosortlayer="below",
      dist=9.9999997473788e-05,
      underground=true,
    },
    {
      anim="backcut_below",
      autosortlayer="below",
      dist=0.50010001659393,
      underground=true,
    },
  },
  proptype=1,
  saturation=-13.0,
  variations=4,
}
