-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_grid_reedsmlblue",
  bank="bandiforest_grid_reedsml",
  brightness=0,
  build="bandiforest_grid_reedsml",
  group="swamp_props",
  hue=0,
  looping=true,
  parallax={
    { anim="bluefront", dist=-0.20000000298023, shadow=true,},
    { anim="bluemid", shadow=true,},
    { anim="blueback", dist=0.30000001192093, shadow=true,},
  },
  randomstartframe=true,
  saturation=0,
}
