-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandicoot_town_bossstatue",
  bank="town_grid_bossstatues",
  build="town_grid_bossstatues",
  clickable=true,
  gridsize={ { h=4, w=4,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="statuem1", shadow=true,},
    { anim="statuef1", dist=-0.30000001192093, shadow=true,},
    { anim="statueb1", dist=0.30000001192093, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=2,
  physicstype="smdec",
  placer=true,
}
