-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_bg_lilypad",
  fade={ bottom=-3.7, top=0.53,},
  group="swamp_props",
  hue=-17.0,
  layer="auto",
  parallax={
    { anim="front_above", autosortlayer="above", dist=-0.5,},
    { anim="mid_above", autosortlayer="above",},
    { anim="back_above", autosortlayer="above", dist=0.5,},
    {
      anim="front_below",
      autosortlayer="below",
      dist=-0.50010001659393,
      underground=true,
    },
    {
      anim="mid_below",
      autosortlayer="below",
      dist=9.9999997473788e-05,
      underground=true,
    },
    {
      anim="back_below",
      autosortlayer="below",
      dist=0.50010001659393,
      underground=true,
    },
  },
  proptype=1,
  saturation=-13.0,
  variations=4,
}
