-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_grid_reedsml",
  brightness=0,
  group="swamp_props",
  hue=0,
  looping=true,
  parallax={
    { anim="front", dist=-0.20000000298023, shadow=true,},
    { anim="mid", shadow=true,},
    { anim="back", dist=0.30000001192093, shadow=true,},
  },
  randomstartframe=true,
  saturation=0,
}
