-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_bg_deadbug",
  fade={ bottom=-3.88, top=1.24,},
  group="swamp_props",
  layer="auto",
  parallax={
    { anim="mainbugf", autosortlayer="below", dist=-1.0, underground=true,},
    { anim="mainbugm_above", autosortlayer="above",},
    { anim="mainbugb_above", autosortlayer="above", dist=2.0,},
    {
      anim="mainbugm_below",
      autosortlayer="below",
      dist=9.9999997473788e-05,
      underground=true,
    },
    {
      anim="mainbugb_below",
      autosortlayer="below",
      dist=2.0000998973846,
      underground=true,
    },
  },
  proptype=1,
  randomize=true,
}
