-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_grid_reed",
  brightness=0,
  group="swamp_props",
  hue=0,
  looping=true,
  parallax={
    { anim="front", dist=-0.3, shadow=true,},
    { anim="mid", shadow=true,},
    { anim="back", dist=0.5, shadow=true,},
  },
  randomstartframe=true,
  saturation=0,
}
