-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_ul_fartreelrg",
  bank="bandiforest_ul_fartree",
  build="bandiforest_ul_fartree",
  fade={ bottom=-3.56, top=-0.25,},
  group="swamp_props",
  layer="auto",
  parallax={
    { anim="lrgtree_above", autosortlayer="above",},
    {
      anim="lrgtree_below",
      autosortlayer="below",
      dist=9.9999997473788e-05,
      underground=true,
    },
  },
  proptype=1,
  randomize=true,
  variations=4,
}
