-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_bg_lrgtree_cuts",
  bank="bandiforest_bg_lrgtree",
  bloom=42.0,
  bloomtargets={ { name="bloom_me", type="Symbol",},},
  build="bandiforest_bg_lrgtree",
  fade={ bottom=-3.88, top=1.24,},
  glowcolor="7E2D6DFF",
  group="swamp_props",
  layer="auto",
  parallax={
    { anim="frontcut", autosortlayer="above", dist=-0.25,},
    { anim="midcut_above", autosortlayer="above",},
    { anim="backcut", autosortlayer="above", dist=1.0,},
    {
      anim="midcut_below",
      autosortlayer="below",
      dist=9.9999997473788e-05,
      underground=true,
    },
  },
  proptype=1,
  randomize=true,
  variations=4,
}
