-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bandiforest_bg_bugwings",
  bank="bandiforest_bg_deadbug",
  build="bandiforest_bg_deadbug",
  fade={ bottom=-3.88, top=1.24,},
  group="swamp_props",
  layer="auto",
  parallax={
    { anim="wingf", autosortlayer="below", underground=true,},
    { anim="wingb_above", autosortlayer="above", dist=1.6000000238419,},
    {
      anim="wingb_below",
      autosortlayer="below",
      dist=1.6001000404358,
      underground=true,
    },
  },
  proptype=1,
}
