-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bed_swamp_1",
  clickable=true,
  gridsize={ { h=2, w=3,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  looping=true,
  networked=1,
  parallax={
    { anim="leg_front", dist=-0.4, shadow=true,},
    { anim="frame_front", dist=-0.2, shadow=true,},
    { anim="frame_back", shadow=true,},
    { anim="leg_back", dist=0.0099999997764826, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=2,
  physicstype="smdec",
  placer=true,
  randomstartframe=true,
}
