-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="bulbug_sm_plushies",
  bank="plushies",
  build="plushies",
  clickable=true,
  gridsize={ { h=1, w=1,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="sm_front9", dist=-0.20000000298023, shadow=true,},
    { anim="sm_mid9", shadow=true,},
    { anim="sm_back9", dist=0.10000000149012, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=0.5,
  physicstype="smdec",
  placer=true,
}
