-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="character_customizer_vshack",
  bank="vanity_table",
  bloom=27.0,
  bloomtargets={ { name="bloom_me", type="Symbol",},},
  build="vanity_table",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="town_decor",
  looping=true,
  parallax={
    { anim="front", dist=-0.4, shadow=true,},
    { anim="mid", shadow=true,},
    { anim="back", dist=0.10000000149012, shadow=true,},
  },
  physicssize=1.2,
  physicstype="dec",
  randomstartframe=true,
  script="screenopener",
  script_args={ screen_require="screens.character.characterscreen",},
  sound=true,
  variations=1,
}
