-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="chemist_unlocked",
  bank="chemist_2",
  build="chemist_2",
  gridsize={ { h=6, w=10,},},
  group="town_buildings",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={ { anim="rough",},},
  parallax_use_baseanim_for_idle=true,
  physicssize=5,
  physicstype="dec",
  script="buildings",
  script_args={ skins={ groups={  }, sets={  }, symbols={  },}, upgrades={  },},
  sound=true,
}
