-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="chemist_locked",
  gridsize={ { h=6, w=10,},},
  group="town_buildings",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="1", dist=-2.5, shadow=true,},
    { anim="2", dist=-1.6000000238419, shadow=true,},
    { anim="3", dist=-0.30000001192093, shadow=true,},
    { anim="4", shadow=true,},
    { anim="5", dist=0.40000000596046, shadow=true,},
    { anim="6", dist=1.0, shadow=true,},
    { anim="7", dist=2.0, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=4,
  physicstype="dec",
}
