-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="corestone_converter_decor3",
  bank="corestone_converter_decor",
  build="corestone_converter_decor",
  gridsize={ { h=3, w=3,},},
  parallax={
    { anim="zero",},
    { anim="three", dist=0.233000010252, shadow=true, xoffset=1.0550000667572,},
    { anim="four", dist=-0.035999983549118, shadow=true, xoffset=1.0550000667572,},
    { anim="three", dist=-0.27500000596046, shadow=true, xoffset=1.0550000667572,},
    { anim="six", dist=-0.46199998259544, shadow=true, xoffset=0.60799998044968,},
    { anim="three", dist=-0.71400001645088, shadow=true, xoffset=0.11699998378754,},
    { anim="four", dist=-0.95600000023842, shadow=true, xoffset=0.125,},
    { anim="three", dist=-1.1400000154972, shadow=true, xoffset=0.12900000810623,},
    { anim="nine", dist=-1.3030000030994, shadow=true, xoffset=-0.44400000572205,},
    { anim="two", dist=0.46100000839215, shadow=true, xoffset=0.16600000858307,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.73,
  physicstype="dec",
  variations=2,
}
