-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="corestone_converter_decor4",
  bank="corestone_converter_decor",
  build="corestone_converter_decor",
  gridsize={ { h=3, w=3,},},
  parallax={
    { anim="zero",},
    { anim="eight", dist=-0.908999979496, shadow=true, xoffset=0.003000000026077,},
    { anim="four", dist=-0.71799999475479, shadow=true, xoffset=-1.0,},
    { anim="three", dist=-0.3759999871254, shadow=true, xoffset=-1.0080000162125,},
    { anim="six", dist=-0.064000003039837, shadow=true, xoffset=-0.51599997282028,},
    { anim="three", dist=0.21500000357628, shadow=true, xoffset=-0.097999997437,},
    { anim="four", dist=0.48699998855591, xoffset=-0.11299999803305,},
    { anim="three", dist=0.75999999046326, xoffset=-0.13199999928474,},
    { anim="nine", dist=0.98100000619888, flip=true, xoffset=0.41699999570847,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.55,
  physicstype="dec",
  variations=2,
}
