-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="corestone_converter_1p",
  bank="corestone_converter",
  bloom=75.0,
  bloomtargets={ { name="bloom", type="Layer",},},
  build="corestone_converter",
  gridsize={ { h=6, w=6,},},
  parallax={
    { anim="1pFloor", onground=true,},
    { anim="1pBloom1", dist=-0.72899997234344, shadow=true,},
    { anim="1", dist=-0.72699999809265, shadow=true,},
    { anim="1pBloom2", dist=-0.003000000026077, shadow=true,},
    { anim="2", dist=-0.0010000000474975, shadow=true,},
    { anim="3", dist=0.38100001215935, shadow=true,},
  },
  physicssize=2.75,
  physicstype="smdec",
  script="metaprogressstore",
  script_args={
    currency="Meta",
    interact_radius=4,
    meta_progress="BIOME_EXPLORATION",
    player_binding="Player 1",
    purchase_type="BiomeExploration",
    status_widget_location="Prop",
  },
  silhouette=true,
}
