-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="corestone_converter_decor2",
  bank="corestone_converter_decor",
  build="corestone_converter_decor",
  gridsize={ { h=3, w=2,},},
  parallax={
    { anim="zero",},
    { anim="three", dist=0.41999998688698, shadow=true, xoffset=0.391999989748,},
    { anim="four", dist=0.11599999666214, shadow=true, xoffset=0.38800001144409,},
    { anim="five", dist=-0.071000002324581, shadow=true, xoffset=0.59799998998642,},
    { anim="three", dist=-0.33300000429153, shadow=true, xoffset=0.85300004482269,},
    { anim="four", dist=-0.625, shadow=true, xoffset=0.84300005435944,},
    { anim="six", dist=-0.87800002098083, shadow=true, xoffset=0.38599997758865,},
    { anim="three", dist=-1.1380000114441, shadow=true, xoffset=-0.13699999451637,},
    { anim="seven", dist=-1.3949999809265, shadow=true, xoffset=-0.13099998235703,},
    { anim="two", dist=0.65600001811981, shadow=true, xoffset=-0.50599998235703,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.7,
  physicstype="vert_obs",
  variations=2,
}
