-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="corestone_converter_decor1",
  bank="corestone_converter_decor",
  build="corestone_converter_decor",
  gridsize={ { h=1, w=1,},},
  parallax={ { anim="one", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  variations=2,
}
