-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="corestone_converter_decor5",
  bank="corestone_converter_decor",
  build="corestone_converter_decor",
  gridsize={ { h=3, w=3,},},
  parallax={
    { anim="zero",},
    { anim="eight", dist=-1.0809999853373, shadow=true, xoffset=0.9759999900125,},
    { anim="four", dist=-0.89000000059605, shadow=true, xoffset=-0.02700001001358,},
    { anim="three", dist=-0.54799999296666, shadow=true, xoffset=-0.03500002622608,},
    {
      anim="six",
      dist=-0.27600000798702,
      flip=true,
      shadow=true,
      xoffset=-0.5799999833107,
    },
    { anim="three", dist=-0.01800000667572, shadow=true, xoffset=-1.0070000290871,},
    { anim="four", dist=0.2589999884367, xoffset=-1.0259999632835,},
    { anim="three", dist=0.56200002133846, xoffset=-1.033999979496,},
    { anim="nine", dist=0.80900000035763, flip=true, xoffset=-0.49400001764297,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.5,
  physicstype="dec",
  variations=2,
}
