-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="dummy_toot",
  bank="dummy_toot",
  build="dummy_toot",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="town_decor",
  parallax={ { anim="main", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  physicssize=0.8,
  physicstype="dec",
  script="dummies",
  sound=true,
}
