-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="forge_locked",
  gridsize={ { h=6, w=10,},},
  group="town_buildings",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="1", dist=-1.8999999761581, shadow=true,},
    { anim="2", dist=-1.7000000476837, shadow=true,},
    { anim="3", dist=-0.5, shadow=true,},
    { anim="4", dist=-0.20000000298023, shadow=true,},
    { anim="5", shadow=true,},
    { anim="6", dist=0.20000000298023, shadow=true,},
    { anim="7", dist=0.30000001192093, shadow=true,},
    { anim="8", dist=1.7999999523163, shadow=true,},
    { anim="9", dist=1.8999999761581, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=5,
  physicstype="dec",
}
