-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="fruit_basket",
  bank="basket",
  build="basket",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="front1", dist=-0.20000000298023, shadow=true,},
    { anim="mid1", shadow=true,},
    { anim="back1", dist=0.20000000298023, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  placer=true,
}
