-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="gourdo_mid_plushies",
  bank="plushies",
  build="plushies",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="mid_front2", dist=-0.2, shadow=true,},
    { anim="mid_mid2", dist=-0.1, shadow=true,},
    { anim="mid_leg2", shadow=true,},
    { anim="mid_back2", dist=0.1, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  placer=true,
}
