-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="inventory_chest",
  bank="inventory_chest",
  bankfile="inventory_chest",
  build="inventory_chest",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  parallax={ { anim="chest", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  physicssize=1.5,
  physicstype="obs",
  script="screenopener",
  script_args={ screen_require="screens.town.inventorychestscreen",},
  sound=true,
}
