-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="lamp_swamp_2",
  bloom=60.0,
  bloomtargets={ { name="bloom", type="Symbol",}, { name="lamp", type="Layer",},},
  children={  },
  glowcolor="FFC900FF",
  gridsize={ { h=1, w=1,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  looping=true,
  networked=1,
  parallax={ { anim="1", dist=-0.0099999997764826, shadow=true,}, { anim="2", shadow=true,},},
  physicssize=0.3,
  physicstype="smdec",
  placer=true,
  randomstartframe=true,
}
