-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="marketroom_rug_big",
  bank="marketroom_rug",
  brightness=0,
  build="marketroom_rug",
  gridsize={ { h=2, level=-1, w=2,},},
  group="shop_props",
  hue=0,
  layer="bg",
  onground=true,
  parallax={ { anim="5",},},
  parallax_use_baseanim_for_idle=true,
  saturation=0,
  sortorder=2,
}
