-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="pergola",
  clickable=true,
  gridsize={ { h=4, w=4,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  looping=true,
  networked=1,
  parallax={
    { anim="front", dist=-1, shadow=true,},
    { anim="mid", shadow=true,},
    { anim="back", dist=1.0, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  placer=true,
  randomstartframe=true,
  variations=1,
}
