-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="player_totem",
  animhistory=true,
  gridsize={ { h=2, w=2,},},
  group="skill_prefabs",
  looping=true,
  networked=1,
  nonpersist=true,
  parallax={ { anim="casting", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  physicssize=0.75,
  physicstype="smdec",
  randomstartframe=true,
  script="totem",
  sound=true,
}
