-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="refinery_unlocked",
  bank="refinery_2",
  build="refinery_2",
  gridsize={ { h=6, w=6,},},
  group="town_buildings",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={ { anim="rough",},},
  parallax_use_baseanim_for_idle=true,
  physicssize=3,
  physicstype="smdec",
  script="buildings",
  script_args={ skins={ groups={  }, sets={  }, symbols={  },}, upgrades={  },},
  sound=true,
}
