-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="refinery_locked",
  gridsize={ { h=6, w=6,},},
  group="town_buildings",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="1", dist=-2.5, shadow=true,},
    { anim="2", dist=-1.2000000476837, shadow=true,},
    { anim="3", dist=-1.0, shadow=true,},
    { anim="4", shadow=true,},
    { anim="5", dist=1.0, shadow=true,},
    { anim="6", dist=1.7000000476837, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=4,
  physicstype="smdec",
}
