-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="rustic_weapon_rack",
  bank="weapon_rack",
  build="weapon_rack",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="front2", dist=-0.4, shadow=true,},
    { anim="weapons2", dist=-0.15, shadow=true,},
    { anim="mid2", shadow=true,},
    { anim="back2", dist=0.05, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.3,
  physicstype="smdec",
  placer=true,
}
