-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="slowpoke_mid_plushies",
  bank="plushies",
  build="plushies",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="mid_front7", dist=-0.30000001192093, shadow=true,},
    { anim="mid_mid7", dist=-0.20000000298023, shadow=true,},
    { anim="mid_leg7", shadow=true,},
    { anim="mid_back7", dist=0.15000000596046, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  placer=true,
}
