-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="stool_outdoor_seating_forest_1",
  bank="outdoor_seating_forest_1",
  build="outdoor_seating_forest_1",
  clickable=true,
  gridsize={ { h=1, w=1,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={ { anim="stool", shadow=true,},},
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  placer=true,
  variations=2,
}
