-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="stool_outdoor_seating_basic",
  bank="outdoor_seating_basic",
  build="outdoor_seating_basic",
  clickable=true,
  gridsize={ { h=1, w=1,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="stool_front", dist=-0.2, shadow=true,},
    { anim="stool_back", shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1,
  physicstype="smdec",
  placer=true,
  variations=2,
}
