-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="straw_wooden_cart",
  bank="wooden_cart",
  build="wooden_cart",
  clickable=true,
  gridsize={ { h=3, w=3,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="front2", dist=-0.4, shadow=true,},
    { anim="mid2", dist=-0.3, shadow=true,},
    { anim="good2", shadow=true,},
    { anim="back2", dist=0.1, shadow=true,},
    { anim="back_wheel2", dist=0.3, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.8,
  physicstype="smdec",
  placer=true,
}
