-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="thatcher_lrg_plushies",
  bank="plushies",
  build="plushies",
  clickable=true,
  gridsize={ { h=2, w=2,},},
  group="construct_structure",
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="lrg_front1", dist=-0.3, shadow=true,},
    { anim="lrg_mid1", dist=-0.1, shadow=true,},
    { anim="lrg_leg1", shadow=true,},
    { anim="lrg_back1", dist=0.1, shadow=true,},
  },
  parallax_use_baseanim_for_idle=true,
  physicssize=1.3,
  physicstype="smdec",
  placer=true,
}
