-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_flower_bush",
  bank="flower_bush",
  brightness=-12.0,
  build="flower_bush",
  gridsize={ { h=2, w=2,},},
  group="construct_decor",
  hostspawn=true,
  isminimal=true,
  looping=true,
  networked=1,
  parallax={
    { anim="front", dist=-0.38, shadow=true,},
    { anim="2", dist=-0.25, shadow=true,},
    { anim="mid", shadow=true,},
    { anim="back", dist=0.25,},
  },
  parallax_use_baseanim_for_idle=true,
  placer=true,
  randomstartframe=true,
  saturation=-9.0,
}
