-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_grid_wall_new",
  brightness=-8.0,
  fade={ bottom=-2.94, top=1.42,},
  group="town_bg_props",
  hue=-7.0,
  layer="auto",
  parallax={
    {
      anim="rubble_below",
      autosortlayer="below",
      dist=-0.10010000318289,
      underground=true,
    },
    { anim="rubble_above", autosortlayer="above", dist=-0.10000000149012,},
    { anim="wall_above", autosortlayer="above",},
    {
      anim="wall_below",
      autosortlayer="below",
      dist=9.9999997473788e-05,
      underground=true,
    },
    { anim="back_above", autosortlayer="above", dist=0.40000000596046,},
    {
      anim="back_below",
      autosortlayer="below",
      dist=0.40009999275208,
      underground=true,
    },
  },
  proptype=1.0,
  saturation=9.0,
  variations=4,
}
