-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_shrub",
  bank="shrub",
  brightness=-17.0,
  build="shrub",
  gridsize={ { h=2, w=2,},},
  group="construct_decor",
  hostspawn=true,
  hue=6.0,
  isminimal=true,
  looping=true,
  networked=1,
  parallax={
    { anim="town1", dist=-0.6,},
    { anim="town2", dist=-0.4,},
    { anim="town3", shadow=true,},
  },
  placer=true,
  randomstartframe=true,
  saturation=0,
}
