-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_grid_helilamp",
  bloom=50.0,
  bloomtargets={ { name="bloom_me", type="Layer",},},
  children={  },
  gridsize={ { h=1, w=1,},},
  group="town_bg_props",
  parallax={
    { anim="lampf", shadow=true,},
    { anim="lampb", dist=0.15000000596046, shadow=true,},
  },
  physicssize=0.3,
  physicstype="smdec",
  placer=true,
}
