-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_bg_helilamp",
  bloom=73.0,
  bloomtargets={ { name="bloom_me", type="Layer",},},
  fade={ bottom=-2.31, top=-0.22,},
  glowcolor="CBD44BFF",
  group="town_bg_props",
  layer="auto",
  parallax={ { anim="lamp",},},
  proptype=1.0,
}
