-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_energy_well_pillar_tundra",
  bank="town_grid_heartpillars",
  bloom=65.0,
  bloomtargets={
    { name="fx_player_untex", type="Symbol",},
    { name="bloom_me_untex", type="Symbol",},
  },
  build="town_grid_heartpillar_tundra",
  gridsize={ { h=2, w=2,},},
  hostspawn=true,
  isminimal=true,
  networked=1,
  parallax={
    { anim="Mid", shadow=true,},
    { anim="BackLShort", dist=0.37000000476837, shadow=true,},
    { anim="BackRShort", dist=0.44999998807907, shadow=true,},
  },
  physicssize=1.2,
  physicstype="smdec",
  script="energywellpillar",
  script_args={ biome_id="tundra",},
}
