-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="town_floor_ruin",
  bloom=41.0,
  bloomtargets={ { name="glow", type="Layer",},},
  glowcolor="AA2BD5FF",
  gridsize={ { h=10, w=10,},},
  group="town_bg_props",
  layer="bg",
  lightoverride=41.0,
  lighttargets={ { name="glow", type="Layer",},},
  onground=true,
  parallax={ { anim="idle",},},
  parallax_use_baseanim_for_idle=true,
  sortorder=2,
}
