-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="trap_acidgeyser",
  bloom=24.0,
  bloomtargets={ { name="bomb", type="Symbol",},},
  fade={ bottom=-1.49, top=0.7,},
  glowcolor="00D451FF",
  group="trap_props",
  hostspawn=true,
  layer="auto",
  networked=1,
  parallax_use_baseanim_for_idle=true,
  proptype=1.0,
  script="trap",
  script_args={
    prefabs={ "thatcher_acid_geyser_left", "thatcher_acid_geyser_right",},
    tier=1.0,
    trap_type="trap_acidgeyser",
  },
}
