-- Generated by PropEditor and loaded by prop_autogen.lua
return {
  __displayName="trap_acid_stage",
  bank="fx_acid",
  build="fx_acid",
  group="trap_props",
  hostspawn=true,
  isminimal=true,
  layer="bg",
  networked=1,
  onground=true,
  parallax_use_baseanim_for_idle=true,
  script="trap",
  script_args={ prefabs={  }, trap_type="trap_acid_stage",},
  sortorder=2,
}
