-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_bandiforest_bg_deadbug",
  isfinal=true,
  prefab={ "bandiforest_bg_deadbug",},
  stategraphs={
    bandiforest_bg_deadbug={
      events={
        idle={
          {
            eventtype="spawneffect",
            frame=1,
            param={
              fxname="lightrays_spotlight_thatcher",
              ischild=true,
              offx=0.0,
              offy=0.0,
              offz=-2.0,
              scalex=3.0,
              scalez=0.80000001192093,
            },
          },
        },
      },
    },
  },
}
