-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_character_customizer_vshack",
  isfinal=true,
  prefab={ "character_customizer_vshack",},
  stategraphs={
    character_customizer_vshack={
      events={
        idle={
          {
            eventtype="spawnparticles",
            frame=1,
            param={
              followsymbol="animated_mirror",
              ischild=true,
              offx=-30.0,
              offy=20.0,
              offz=0.0,
              particlefxname="vanity_table_stars",
            },
          },
        },
      },
    },
  },
}
