-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_ground_indicator_ring_p1",
  isfinal=true,
  prefab={ "ground_indicator_ring_p1",},
  stategraphs={
    ground_indicator_ring_p1={
      events={
        idle={
          {
            eventtype="spawnparticles",
            frame=13,
            param={ followsymbol="ring_untex", ischild=true, particlefxname="ground_glow_p1",},
          },
          {
            eventtype="spawneffect",
            frame=13,
            param={
              fxname="ground_indicator_beam_p1",
              ischild=true,
              scalex=0.80000001192093,
              scalez=1.0,
              stopatexitstate=true,
            },
          },
        },
      },
    },
  },
}
