-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_ground_target_jamball_dormant_p1",
  isfinal=true,
  prefab={ "fx_ground_target_jamball_dormant_p1",},
  stategraphs={
    fx_ground_target_jamball_dormant_p1={
      events={
        idle={
          {
            eventtype="spawneffect",
            frame=0,
            param={
              fxname="ground_indicator_beam_p1",
              ischild=true,
              scalex=1.7999999523163,
              scalez=1.2000000476837,
              stopatexitstate=true,
            },
          },
        },
      },
    },
    ground_indicator_ring_p1={
      events={
        idle={
          {
            eventtype="spawneffect",
            frame=13,
            param={ fxname="ground_indicator_beam_p1", ischild=true, stopatexitstate=true,},
          },
        },
      },
    },
  },
}
