-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_power_pickup_single",
  isfinal=true,
  prefab={ "power_pickup_single",},
  stategraphs={ sg_shopitem={ events={ despawn={  }, idle={  }, spawn={  },},},},
}
