-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_swarmy",
  isfinal=true,
  prefab={ "swarmy", "swarmy_elite",},
  stategraphs={
    sg_swarmy={
      sg_events={
        {
          eventtype="spawneffect",
          name="vfx-acid_burst",
          param={ fxname="fx_ring_liquid", scalex=1.8999999761581, scalez=1.8999999761581,},
        },
        {
          eventtype="spawneffect",
          name="vfx-acid_burst",
          param={ fxname="fx_swarmy_acid_burst", scalex=1.3500000238419, scalez=1.3500000238419,},
        },
        {
          eventtype="spawnparticles",
          name="vfx-acid_dash",
          param={
            ischild=true,
            particlefxname="swarmy_dash_trail",
            render_in_front=true,
            stopatexitstate=true,
            use_entity_facing=true,
          },
        },
        {
          eventtype="spawneffect",
          name="vfx-swarmy_uppercut",
          param={
            fxname="fx_swarmy_uppercut",
            inheritrotation=true,
            ischild=true,
            stopatexitstate=true,
          },
        },
        {
          eventtype="spawneffect",
          name="vfx-uppercut_land",
          param={
            fxname="fx_swarmy_uppercut_land",
            offx=0.0,
            offy=0.0,
            offz=0.0,
            scalex=1.3999999761581,
            scalez=0.80000001192093,
          },
        },
      },
    },
  },
}
