-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_totolili_elite_projectile",
  isfinal=true,
  prefab={ "totolili_elite_projectile",},
  stategraphs={
    sg_totolili_projectile={
      events={
        death={
          {
            eventtype="spawnparticles",
            frame=1,
            param={ duration=50.0, particlefxname="totolili_elite_hat_death_burst",},
          },
        },
      },
      sg_events={
        {
          eventtype="spawnparticles",
          name="vfx-lily_hat_spin_loop",
          param={
            followsymbol="hat",
            ischild=true,
            name="hat_trail",
            particlefxname="totolili_elite_hat_trail",
            use_entity_facing=true,
          },
        },
        {
          eventtype="spawneffect",
          name="vfx-lily_hat_spin_loop",
          param={
            fxname="fx_totolili_elite_projectile_hat",
            inheritrotation=true,
            ischild=true,
            offx=0.0,
            offy=0.0,
            offz=0.0,
            scalex=1.2000000476837,
            scalez=1.2000000476837,
            stopatexitstate=true,
          },
        },
      },
    },
  },
}
