-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_thatswamp_gate_s",
  isfinal=true,
  prefab={ "thatforest_gate_s",},
  sg_wildcard=true,
  stategraphs={
    ["*"]={
      events={
        idle={  },
        open={
          {
            eventtype="spawnparticles",
            frame=1,
            param={
              offx=0.0,
              offy=0.0,
              offz=-6.6199998855591,
              particlefxname="forest_gate_fog_s",
              render_in_front=true,
              stopatexitstate=true,
            },
          },
          {
            eventtype="spawnparticles",
            frame=1,
            param={ offx=0.0, offy=0.0, offz=-3.75, particlefxname="forest_gate_fog_s_back",},
          },
        },
      },
      sg_events={  },
    },
  },
}
