-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_town_forge_unlocked",
  isfinal=true,
  prefab={ "forge_unlocked",},
  stategraphs={
    forge_unlocked={
      events={
        idle={
          {
            eventtype="spawnparticles",
            frame=1,
            param={
              followsymbol="swap_fx",
              offx=-167.0,
              offy=-1050.0,
              offz=0.0,
              particlefxname="embers_chimney_forgeunlocked",
              render_in_front=true,
            },
          },
        },
      },
    },
  },
}
