-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_totolili_elite",
  isfinal=true,
  prefab={ "totolili_elite",},
  stategraphs={
    sg_totolili={
      sg_events={
        {
          eventtype="spawnparticles",
          name="vfx-lily_toss_spin_pst",
          param={
            duration=50.0,
            offx=0.0,
            offy=2.7000000476837,
            offz=0.0,
            particlefxname="totolili_elite_hat_death_burst",
          },
        },
        {
          eventtype="spawneffect",
          name="vfx-lily_toss",
          param={
            fxname="fx_totolili_throw_elite",
            inheritrotation=true,
            ischild=true,
            offx=0.0,
            offy=0.0,
            offz=-0.10000000149012,
          },
        },
      },
    },
  },
}
