-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_trap_acid_stage",
  isfinal=true,
  prefab={ "trap_acid_stage",},
  stategraphs={
    sg_trap_acid={
      events={
        loop={
          {
            eventtype="spawnparticles",
            frame=1,
            param={ particlefxname="acidpool_trap_loop",},
          },
        },
      },
    },
    sg_trap_acid_stage={
      events={
        land={
          {
            eventtype="spawnparticles",
            frame=1,
            param={ ischild=true, particlefxname="acidpool_trap_pre", stopatexitstate=true,},
          },
          {
            eventtype="spawneffect",
            frame=1,
            param={
              fxname="fx_acidpool_ground_land",
              offx=0.0,
              offy=0.0,
              offz=0.0,
              scalex=4.0,
              scalez=4.0,
            },
          },
          {
            eventtype="spawneffect",
            frame=1,
            param={
              fxname="fx_acid_land_stage",
              offx=0.0,
              offy=0.0,
              offz=0.0,
              scalex=4.0,
              scalez=4.0,
            },
          },
          {
            eventtype="spawneffect",
            frame=1,
            param={ fxname="fx_acid_splash_stage", scalex=1.2000000476837, scalez=1.2000000476837,},
          },
        },
        loop={
          {
            eventtype="spawneffect",
            frame=0,
            param={ fxname="fx_acidpool_ground_loop", scalex=4.0, scalez=4.0, stopatexitstate=true,},
          },
          {
            eventtype="spawnparticles",
            frame=0,
            param={
              ischild=true,
              name="spots",
              particlefxname="acidpool_trap_loop",
              stopatexitstate=true,
            },
          },
        },
        pst={
          {
            eventtype="spawneffect",
            frame=0,
            param={ fxname="fx_acidpool_ground_pst", scalex=4.0, scalez=4.0,},
          },
          {
            eventtype="spawnparticles",
            frame=2,
            param={ name="spots", particlefxname="acidpool_trap_post", stopatexitstate=true,},
          },
        },
      },
    },
  },
}
