-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="fx_woworm",
  isfinal=true,
  prefab={ "woworm", "woworm_elite",},
  stategraphs={
    sg_woworm={
      events={ walk_loop={  },},
      sg_events={
        {
          eventtype="spawneffect",
          name="vfx-puke",
          param={ fxname="fx_woworm_barf", inheritrotation=true, ischild=true,},
        },
        {
          eventtype="spawneffect",
          name="vfx-shellslam_ring",
          param={
            fxname="fx_ring_liquid",
            inheritrotation=true,
            ischild=true,
            offx=0.72000002861023,
            offy=0.0,
            offz=-0.18000000715256,
            scalex=2.0,
            scalez=2.0,
          },
        },
      },
    },
  },
}
