-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="shake_gourdo",
  group="screenshakes",
  isfinal=true,
  prefab={ "gourdo", "gourdo_elite",},
  stategraphs={
    sg_gourdo={
      sg_events={
        {
          eventtype="shakecamera",
          name="shake-butt_slam_elite",
          param={ dist=50, duration=20.0, mode="FULL", speed=0.019999999552965,},
        },
        {
          eventtype="shakecamera",
          name="shake-butt_slam",
          param={
            dist=50,
            duration=20.0,
            mode="FULL",
            scale=0.075000002980232,
            speed=0.019999999552965,
          },
        },
        {
          eventtype="shakecamera",
          name="shake-knockdown",
          param={ dist=50, duration=20.0, mode="FULL", speed=0.019999999552965,},
        },
        {
          eventtype="shakecamera",
          name="shake-spawn",
          param={ dist=50, duration=20.0, mode="VERTICAL", speed=0.019999999552965,},
        },
      },
    },
  },
}
