-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="shake_floracrane",
  group="screenshakes",
  isfinal=true,
  prefab={ "floracrane", "floracrane_elite",},
  stategraphs={
    sg_floracrane={
      sg_events={
        {
          eventtype="shakecamera",
          name="shake-dive",
          param={ dist=50, duration=20.0, mode="FULL", speed=0.019999999552965,},
        },
        {
          eventtype="shakecamera",
          name="shake-hop",
          param={
            dist=25,
            duration=12.0,
            mode="VERTICAL",
            scale=0.075000002980232,
            speed=0.019999999552965,
          },
        },
      },
    },
  },
}
