-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="shake_yammo",
  group="screenshakes",
  isfinal=true,
  prefab={ "yammo", "yammo_elite",},
  stategraphs={
    sg_yammo={
      sg_events={
        {
          eventtype="shakecamera",
          name="shake-spawn_jump",
          param={ dist=10, duration=10.0, mode="VERTICAL", speed=0.019999999552965,},
        },
        {
          eventtype="shakecamera",
          name="shake-heavy_slam",
          param={ dist=20, duration=10.0, mode="VERTICAL", speed=0.019999999552965,},
        },
        {
          eventtype="shakecamera",
          name="shake-knockdown",
          param={ dist=20, duration=19.0, mode="VERTICAL", speed=0.019999999552965,},
        },
        {
          eventtype="shakecamera",
          name="shake-elite_heavy_slam",
          param={ dist=50, duration=20.0, mode="FULL", speed=0.019999999552965,},
        },
        {
          eventtype="shakecamera",
          name="shake-run",
          param={ dist=50, duration=12.0, mode="VERTICAL", speed=0.019999999552965,},
        },
      },
    },
  },
}
