-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_swarmy",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "swarmy", "swarmy_elite",},
  stategraphs={
    sg_swarmy={
      sg_events={
        { eventtype="playfoleysound", name="sfx-footstep", param={ soundtag="Footstep",},},
        { eventtype="playfoleysound", name="sfx-bodyfall", param={ soundtag="Bodyfall",},},
        {
          eventtype="playsound",
          name="sfx-knockdown",
          param={ autostop=true, soundevent="Knockdown",},
        },
        {
          eventtype="playsound",
          name="sfx-knockdown_hold",
          param={ soundevent="swarmy_knockdown_hold",},
        },
        {
          eventtype="playsound",
          name="sfx-acidburst",
          param={ soundevent="swarmy_splat",},
        },
        {
          eventtype="playsound",
          name="sfx-vo_short",
          param={ soundevent="swarmy_vo_short1",},
        },
        { eventtype="playsound", name="sfx-dash", param={ soundevent="swarmy_dash",},},
        {
          eventtype="playsound",
          name="sfx-vo_long",
          param={ soundevent="swarmy_vo_long",},
        },
        {
          eventtype="playfoleysound",
          name="sfx-bodyfall_q",
          param={ soundtag="Bodyfall", volume=29.0,},
        },
        {
          eventtype="playsound",
          name="sfx-tell",
          param={ soundevent="AAAA_default_event",},
        },
        {
          eventtype="playsound",
          name="sfx-punch",
          param={ soundevent="swarmy_uppercut",},
        },
        { eventtype="playsound", name="sfx-hit", param={ soundevent="swarmy_vo_hit",},},
        { eventtype="playsound", name="sfx-be2", param={ soundevent="swarmy_be2",},},
      },
    },
  },
}
