-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_totolili_projectile",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "totolili_projectile", "totolili_elite_projectile",},
  stategraphs={
    sg_totolili_projectile={
      events={
        death={
          { eventtype="stopsound", frame=1, param={ name="spin_LP",},},
          { eventtype="playsound", frame=1, param={ soundevent="totolili_rip",},},
        },
        spiral={
          {
            eventtype="playsound",
            frame=1,
            param={ autostop=true, name="spin_LP", soundevent="totolili_spin_LP",},
          },
        },
        thrown={
          {
            eventtype="playsound",
            frame=1,
            param={ autostop=true, name="spin_LP", soundevent="totolili_spin_LP",},
          },
        },
        thrown_hold={
          {
            eventtype="playsound",
            frame=1,
            param={ autostop=true, name="spin_LP", soundevent="totolili_spin_LP",},
          },
        },
        thrown_return={
          {
            eventtype="playsound",
            frame=1,
            param={ autostop=true, name="spin_LP", soundevent="totolili_spin_LP",},
          },
        },
      },
    },
  },
}
