-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_woworm_shell",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "woworm_shell", "woworm_shell_elite",},
  stategraphs={
    sg_woworm_shell={
      sg_events={
        { eventtype="playsound", name="sfx-hit", param={ soundevent="woworm_shell_hit",},},
        {
          eventtype="playsound",
          name="sfx-foley",
          param={ soundevent="woworm_shell_foley",},
        },
        {
          eventtype="playsound",
          name="sfx-death",
          param={ soundevent="Destructible_rock",},
        },
      },
    },
  },
}
