-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_thatcher_acid_geyser",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "thatcher_acid_geyser_left", "thatcher_acid_geyser_right",},
  stategraphs={
    sg_thatcher_acid_geyser={
      events={
        pre={
          { eventtype="playsound", frame=1, param={ soundevent="thatcher_geyser_explode",},},
          {
            eventtype="playsound",
            frame=6,
            param={ autostop=true, name="geyser_LP", soundevent="thatcher_geyser_LP",},
          },
        },
        pst={
          { eventtype="stopsound", frame=1, param={ name="geyser_LP",},},
          { eventtype="playsound", frame=1, param={ soundevent="thatcher_acid_splash",},},
        },
      },
    },
  },
}
