-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_player_skills",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "player_side",},
  sg_wildcard=true,
  stategraphs={
    ["*"]={
      events={
        idle_blink={  },
        skill_cannon_singlereload={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="Skill_Cannon_ReloadAmmo", volume=0.0,},
          },
        },
        skill_cannon_singlereload_no={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="Skill_Cannon_ReloadAmmo_full",},
          },
        },
        skill_cannon_singlereload_yes_loop={
          { eventtype="playsound", frame=1, param={ soundevent="Skill_Cannon_ReloadAmmo",},},
        },
      },
      sg_events={
        {
          eventtype="playsound",
          name="sfx-ground_thrust_charge",
          param={
            name="Skill_Ground_Thrust_Charge",
            sound_max_count=1.0,
            soundevent="Skill_groundThrust_Charge",
            stopatexitstate=true,
          },
        },
        {
          eventtype="playsound",
          name="banana_eat",
          param={ sound_max_count=1.0, soundevent="Skill_BananaPeel_Eat",},
        },
        {
          eventtype="playsound",
          name="banana_land",
          param={ sound_max_count=1.0, soundevent="Skill_BananaPeel_Land",},
        },
        {
          eventtype="playsound",
          name="banana_toss",
          param={ sound_max_count=1.0, soundevent="Skill_BananaPeel_Toss",},
        },
        {
          eventtype="playsound",
          name="throw_stone_charge",
          param={
            autostop=true,
            sound_max_count=1.0,
            soundevent="Skill_ThrowStone_Charge_LP",
            stopatexitstate=true,
          },
        },
        {
          eventtype="playsound",
          name="sfx-foley_L",
          param={ soundevent="Emote_Mvmt_lg",},
        },
        {
          eventtype="playsound",
          name="sfx-foley_m",
          param={ soundevent="Emote_Mvmt_med",},
        },
        {
          eventtype="playsound",
          name="sfx-foley_sm",
          param={ soundevent="Emote_Mvmt_sm",},
        },
        { eventtype="playfoleysound", name="sfx-footstep", param={ soundtag="Footstep",},},
        { eventtype="playfoleysound", name="sfx-hand", param={ soundtag="Hand",},},
        {
          eventtype="playfoleysound",
          name="sfx-footstep_stop",
          param={ soundtag="Footstep Stop",},
        },
        {
          eventtype="playsound",
          name="sfx-groak_hands",
          param={ soundevent="Skill_groak_vacuum_hands",},
        },
        {
          eventtype="playsound",
          name="sfx-groak",
          param={ soundevent="Skill_groak_vacuum",},
        },
      },
    },
  },
}
