-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_energywell_wellspring_pillar",
  isfinal=true,
  needSoundEmitter=true,
  prefab={
    "town_energy_well_pillar_swamp",
    "town_energy_well_pillar_forest",
    "town_energy_well_pillar_tundra",
  },
  stategraphs={
    sg_energy_well_pillar={
      events={
        powerup={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="Wellspring_Pillar_Activate",},
          },
        },
      },
    },
  },
}
