-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_power_drop_loot_bag",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "power_drop_material",},
  stategraphs={
    sg_konjur_reward_drop={
      events={
        shatter={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="power_drop_material_shatter",},
          },
          { eventtype="stopsound", frame=1, param={ name="idle_LP",},},
        },
        spawn={
          {
            eventtype="playsound",
            frame=1,
            param={ soundevent="powerCrystal_spawn_energy", stopatexitstate=true,},
          },
          {
            eventtype="playsound",
            frame=34,
            param={ soundevent="power_drop_material_spawn",},
          },
          {
            eventtype="playsound",
            frame=34,
            param={ autostop=true, name="idle_LP", soundevent="power_drop_material_idle_LP",},
          },
        },
      },
    },
  },
}
