-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_energy_well",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "town_energy_well",},
  stategraphs={
    sg_energy_well={
      events={
        activate={
          {
            eventtype="playsound",
            frame=1,
            param={ autostop=true, soundevent="Wellspring_Activate", stopatexitstate=true,},
          },
        },
        closed={  },
        excited={
          {
            eventtype="setsoundparameter",
            frame=9,
            param={ param_name="wellspring_bounce", param_value=1, sound_name="wellspring_LP",},
          },
          {
            eventtype="setsoundparameter",
            frame=17,
            param={ param_name="wellspring_bounce", param_value=1, sound_name="wellspring_LP",},
          },
          {
            eventtype="setsoundparameter",
            frame=25,
            param={ param_name="wellspring_bounce", param_value=1, sound_name="wellspring_LP",},
          },
          {
            eventtype="setsoundparameter",
            frame=33,
            param={ param_name="wellspring_bounce", param_value=1, sound_name="wellspring_LP",},
          },
          {
            eventtype="setsoundparameter",
            frame=41,
            param={ param_name="wellspring_bounce", param_value=1, sound_name="wellspring_LP",},
          },
          {
            eventtype="setsoundparameter",
            frame=49,
            param={ param_name="wellspring_bounce", param_value=1, sound_name="wellspring_LP",},
          },
          {
            eventtype="playsound",
            frame=1,
            param={ autostop=true, name="wellspring_LP", soundevent="Wellspring_LP",},
          },
          {
            eventtype="setsoundparameter",
            frame=1,
            param={ param_name="wellspring_bounce", param_value=1, sound_name="wellspring_LP",},
          },
          {
            eventtype="setsoundparameter",
            frame=2,
            param={
              param_name="wellspring_isExcited",
              param_value=1.0099999904633,
              sound_name="wellspring_LP",
            },
          },
        },
        excited_transition={
          { eventtype="playsound", frame=1, param={ soundevent="Wellspring_Shift_Up",},},
          {
            eventtype="setsoundparameter",
            frame=1,
            param={ param_name="wellspring_isExcited", param_value=1, sound_name="wellspring_LP",},
          },
        },
        idle={
          {
            eventtype="playsound",
            frame=1,
            param={ autostop=true, name="wellspring_LP", soundevent="Wellspring_LP",},
          },
          {
            eventtype="setsoundparameter",
            frame=2,
            param={ param_name="wellspring_isExcited", param_value=0.0, sound_name="wellspring_LP",},
          },
          {
            eventtype="setsoundparameter",
            frame=6,
            param={
              param_name="wellspring_shake",
              param_value=1.0099999904633,
              sound_name="wellspring_LP",
            },
          },
          {
            eventtype="setsoundparameter",
            frame=110,
            param={
              param_name="wellspring_pulse",
              param_value=1.0099999904633,
              sound_name="wellspring_LP",
            },
          },
        },
        idle_transition={
          { eventtype="playsound", frame=1, param={ soundevent="Wellspring_Shift_Down",},},
          {
            eventtype="setsoundparameter",
            frame=1,
            param={ param_name="wellspring_isExcited", param_value=0.0, sound_name="wellspring_LP",},
          },
        },
        open={  },
      },
      sg_events={
        {
          eventtype="playsound",
          name="sfx-shake",
          param={ soundevent="Wellspring_Shake_Small", stopatexitstate=true,},
        },
        {
          eventtype="playsound",
          name="sfx-tick_backward",
          param={ soundevent="Wellspring_Gear_Tick_Backward",},
        },
        {
          eventtype="playsound",
          name="sfx-gear_forward_slow",
          param={ soundevent="Wellspring_Gear_Tick_Forward_Slow",},
        },
        {
          eventtype="playsound",
          name="sfx-rattle",
          param={ soundevent="Wellspring_Rattle", stopatexitstate=true,},
        },
        {
          eventtype="playsound",
          name="sfx-tick_forward_fast",
          param={ soundevent="Wellspring_Gear_Tick_Forward_Fast",},
        },
      },
    },
  },
}
