-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_heartstone",
  isfinal=true,
  needSoundEmitter=true,
  prefab={
    "soul_drop_boss_megatreemon",
    "soul_drop_boss_bandicoot",
    "soul_drop_boss_owlitzer",
    "soul_drop_boss_thatcher",
  },
  stategraphs={
    sg_rotating_drop={
      events={
        idle={
          {
            eventtype="playsound",
            frame=1,
            param={
              autostop=true,
              name="heartstone_idle_LP",
              soundevent="konjurHeart_idle_LP",
              stopatexitstate=true,
            },
          },
        },
        spawn={
          {
            eventtype="playsound",
            frame=65,
            param={ autostop=true, name="heartstone_idle_LP", soundevent="konjurHeart_idle_LP",},
          },
          { eventtype="stopsound", frame=38, param={ name="heartstone_spawn_energy",},},
        },
      },
      sg_events={
        {
          eventtype="playsound",
          name="sfx-absorb",
          param={ soundevent="konjurHeart_absorb",},
        },
        {
          eventtype="playsound",
          name="sfx-explode",
          param={ sound_max_count=1.0, soundevent="konjurHeart_spawn_explode",},
        },
        {
          eventtype="playsound",
          name="sfx-energy",
          param={
            name="heartstone_spawn_energy",
            sound_max_count=1.0,
            soundevent="konjurHeart_spawn_energy",
            stopatexitstate=true,
          },
        },
      },
    },
  },
}
