-- Generated by Embellisher and loaded by stategraph_autogen.lua
return {
  __displayName="sound_woworm",
  isfinal=true,
  needSoundEmitter=true,
  prefab={ "woworm", "woworm_elite",},
  stategraphs={
    sg_woworm={
      events={
        barf={  },
        shellslam_hold={
          { eventtype="playsound", frame=1, param={ soundevent="woworm_slam_pre",},},
          { eventtype="playsound", frame=1, param={ soundevent="woworm_slam_pre",},},
        },
        shellslam_pre={  },
      },
      sg_events={
        { eventtype="playfoleysound", name="sfx-footstep", param={ soundtag="Footstep",},},
        { eventtype="playfoleysound", name="sfx-bodyfall", param={ soundtag="Bodyfall",},},
        { eventtype="playsound", name="sfx-foley", param={ soundevent="woworm_foley",},},
        {
          eventtype="playsound",
          name="sfx-breath_out",
          param={ soundevent="woworm_breath_out",},
        },
        {
          eventtype="playsound",
          name="sfx-breath_in",
          param={ soundevent="woworm_breath_in",},
        },
        {
          eventtype="playsound",
          name="sfx-barf_pre",
          param={ soundevent="woworm_puke_pre",},
        },
        { eventtype="playsound", name="sfx-barf", param={ soundevent="woworm_puke",},},
        {
          eventtype="playsound",
          name="sfx-shell_slam",
          param={ soundevent="woworm_slam",},
        },
        { eventtype="playsound", name="sfx-hit", param={ soundevent="woworm_hit",},},
        { eventtype="playsound", name="sfx-tell", param={ soundevent="woworm_tell",},},
        { eventtype="playsound", name="sfx-splash", param={ soundevent="woworm_splash",},},
        { eventtype="playsound", name="sfx-knockdown", param={ soundevent="Knockdown",},},
        { eventtype="playsound", name="sfx-whoosh", param={ soundevent="woworm_whoosh",},},
      },
    },
  },
}
