-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="acid_splatter_burst",
  anim="1",
  autostop=true,
  bank="fx_hits_liquid",
  bloom=75.0,
  brightness=77.0,
  build="fx_hits_liquid",
  glowcolor="2BFF00FF",
  group="hits_fx",
  hue=56.0,
  randomflip=true,
  scalex=2.0,
  scaley=2.0,
  soundevent="slowpoke_acid_splash",
  target_tint="FF640000",
}
