-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="acquire_gourdo_skill_item",
  anim="item_aquire_healseed",
  bank="fx_aquire_item_ui",
  bloom=50.0,
  build="fx_aquire_item_ui",
  glowcolor="AD00FFFF",
  group="UI_items",
  multcolor="FFFFFFCC",
  noflip=true,
}
