-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="death_windmon_elite_grnd",
  anim="death_ground_splash",
  bank="fx_monster_death_untex",
  brightness=-10.0,
  build="fx_monster_death_untex",
  finaloffset=7,
  group="deaths",
  hue=-70.0,
  layer="bg",
  noflip=true,
  onground=true,
  saturation=-88.0,
  scalex=1.2000000476837,
  scaley=1.2000000476837,
  sortorder=2,
}
