-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_acidpool_ground_pst",
  anim="ground_pst_acid",
  bank="fx_acid",
  bloom=10.0,
  brightness=-21.0,
  build="fx_acid",
  group="fx_acid",
  layer="bg",
  multcolor="A6C2FFFF",
  onground=true,
  saturation=57.0,
  scalex=2.7999999523163,
  scaley=2.7999999523163,
  sortorder=2,
}
