-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_acid_splash_stage",
  anim="projectile_land_3",
  autostop=true,
  bank="fx_acid",
  bloom=25.0,
  build="fx_acid",
  group="fx_acid",
  scalex=1.0,
  scaley=1.0,
  soundevent="mossquito_acid",
}
