-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_acid_land_stage",
  anim="acid_land",
  bank="fx_acid",
  bloom=20.0,
  build="fx_acid",
  clip_at_worldedge=true,
  group="fx_acid",
  layer="bg",
  noflip=true,
  onground=true,
  scalex=2.5,
  scaley=2.5,
  sortorder=2,
}
