-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_acid_mudbubble",
  anim="acid_mudbubble",
  autostop=true,
  bank="fx_acid",
  brightness=-50.0,
  build="fx_acid",
  group="fx_acid",
  looping=true,
  multcolor="91FF80CC",
  randomstartframe=true,
  scalex=0.75,
  soundevent="mossquito_acid",
}
