-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_acidpool_bubbles",
  anim="bubble_loop",
  bank="fx_acid",
  bloom=100.0,
  build="fx_acid",
  glowcolor="B9FF00FF",
  group="fx_acid",
  layer="bg",
  looping=true,
  multcolor="80FF80FF",
  randomstartframe=true,
  sortorder=2,
}
