-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_acid_thatcher_bg_geyser_loop",
  anim="loop",
  autostop=true,
  bank="fx_thatcher_acid_geyser",
  bloom=25.0,
  build="fx_thatcher_acid_geyser",
  group="fx_acid",
  soundevent="mossquito_acid",
}
