-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_bandicoot_phase_swipe_1",
  anim="phase_transition_swipe1",
  bank="fx_bandicoot",
  bloom=100.0,
  build="fx_bandicoot",
  finaloffset=1,
  group="fx_bandicoot",
  scalex=1.0,
  scaley=1.0,
}
