-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_bomb_spore_juggernaut",
  anim="juggernaut_spin",
  bank="trap_bomb_spore",
  build="trap_bomb_spore",
  group="bombs_traps",
  looping=true,
  randomstartframe=true,
}
