-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_ground_target_jamball",
  anim="idle_jamball",
  bank="fx_ground_target",
  bloom=50.0,
  brightness=-25.0,
  build="fx_ground_target",
  clip_at_worldedge=true,
  finaloffset=-1,
  glowcolor="FFFFFFFF",
  group="fx_warning",
  looping=true,
  multcolor="FF8F8FE6",
  onground=true,
  randomstartframe=true,
}
