-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_ground_totem_area_pst",
  addcolor="FF000000",
  anim="pst",
  bank="fx_ground_heal_area",
  bloom=52.0,
  build="fx_ground_heal_area",
  clip_at_worldedge=true,
  group="player_skills",
  layer="bg",
  multcolor="FFFFFF80",
  onground=true,
  scalex=5.0,
  scaley=5.0,
  sortorder=2,
}
