-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_player_skills_yammo_swing_focus_lrg",
  additive=true,
  anim="skill_yammo_swing_focus_lrg",
  bank="fx_player_bank_skills_miniboss",
  bloom=100.0,
  build="fx_player_bank_skills_miniboss",
  glowcolor="0074FFFF",
  group="player_skills",
  multcolor="3333FFFF",
}
