-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_polearm_roll_rev_atk_long",
  anim="roll_rev_atk",
  bank="fx_player_bank_polearm_long",
  bloom=49.0,
  build="fx_player_bank_polearm_long",
  finaloffset=1,
  glowcolor="FF9707FF",
  group="fx_polearm_long",
  multcolor="FFFFFFCC",
  scalex=1.0,
  scaley=1.0,
}
