-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_polearm_multithrust_atk_pst_electric",
  anim="polearm_multithrust_atk_pst",
  bank="fx_player_bank_polearm_electric",
  bloom=40.0,
  build="fx_player_bank_polearm_electric",
  glowcolor="FFFE00FF",
  group="fx_polearm_electric",
  multcolor="FFFFFFB3",
}
