-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_player_revive_pre",
  anim="revive_pre",
  bank="fx_player_revive",
  bloom=100.0,
  build="fx_player_revive",
  group="player_skills",
  multcolor="FFFFFF80",
}
