-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_player_skills_yammo_pulse_sml",
  additive=true,
  anim="pulse_sml",
  bank="fx_player_bank_skills_miniboss",
  bloom=100.0,
  build="fx_player_bank_skills_miniboss",
  glowcolor="FF00ECFF",
  group="player_skills",
  multcolor="FFFFFFBF",
}
