-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_polearm_atk_long",
  anim="atk",
  bank="fx_player_bank_polearm_long",
  bloom=100.0,
  build="fx_player_bank_polearm_long",
  finaloffset=1,
  group="fx_polearm_long",
  multcolor="B39999FF",
}
