-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_player_skill_dodge_cancel",
  addcolor="0000FF00",
  anim="dodge_cancel",
  bank="fx_hits_player_skills",
  bloom=100.0,
  build="fx_hits_player_skills",
  glowcolor="00FF51FF",
  group="player_skills",
  layer="bg",
  multcolor="BABAFFFF",
  onground=true,
  scaley=1.5,
  sortorder=2,
  target_tint="FF640000",
}
