-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_player_skills_yammo_loop_med",
  additive=true,
  anim="loop_med",
  bank="fx_player_bank_skills_miniboss",
  bloom=100.0,
  build="fx_player_bank_skills_miniboss",
  glowcolor="FF00ECFF",
  group="player_skills",
  looping=true,
  multcolor="FFFFFFBF",
  randomstartframe=true,
}
