-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_player_skills_floracrane_dive_ol_focus",
  additive=true,
  anim="skill_flora_dive_ol",
  bank="fx_player_bank_skills_miniboss",
  bloom=100.0,
  build="fx_player_bank_skills_miniboss",
  glowcolor="0074FFFF",
  group="player_skills",
  multcolor="6666FFE6",
}
