-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_swarmy_uppercut",
  addcolor="00640000",
  anim="uppercut",
  bank="fx_swarmy",
  bloom=20.0,
  build="fx_swarmy",
  group="creatures",
}
