-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_swamp_stalactite_landed",
  anim="1",
  bank="destructible_bandiforest_ceiling",
  build="destructible_bandiforest_ceiling",
  group="bombs_traps",
  looping=true,
  randomstartframe=true,
}
