-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_skills_gourdo_chainstrike_lrg_2",
  additive=true,
  anim="gourdo_chain_lrg_2",
  bank="fx_hit_gourdo_powers",
  bloom=100.0,
  build="fx_hit_gourdo_powers",
  glowcolor="DBBB18FF",
  group="player_skills",
  multcolor="FFFFFFBF",
  onground=true,
}
