-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_swarmy_uppercut_land",
  anim="acid_land",
  bank="fx_acid",
  bloom=11.0,
  build="fx_acid",
  clip_at_worldedge=true,
  group="creatures",
  layer="bg",
  noflip=true,
  onground=true,
  scalex=1.0,
  scaley=1.0,
  sortorder=2,
}
