-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_totolili_elite_projectile_hat",
  anim="lily_hat_spin_loop",
  bank="fx_totolili",
  bloom=100.0,
  build="fx_totolili",
  glowcolor="FF47CBFF",
  group="creatures",
}
