-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_totolili_throw_elite",
  anim="lily_toss",
  bank="fx_totolili",
  bloom=100.0,
  build="fx_totolili",
  glowcolor="FF48F6FF",
  group="creatures",
}
