-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_totolili_throw",
  anim="lily_toss",
  bank="fx_totolili",
  bloom=100.0,
  build="fx_totolili",
  glowcolor="42FFCDFF",
  group="creatures",
}
