-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_thatcher_acid_blob",
  addcolor="00150000",
  anim="acid_blob",
  bank="fx_thatcher",
  bloom=20.0,
  build="fx_thatcher",
  glowcolor="CDEA11FF",
  group="fx_thatcher",
  looping=true,
  randomstartframe=true,
}
