-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_thatcher_acid_splash",
  addcolor="00640000",
  anim="acid_splash",
  bank="fx_thatcher",
  bloom=20.0,
  build="fx_thatcher",
  group="fx_thatcher",
}
