-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="fx_thatcher_full_swing_mobile_loop",
  addcolor="00640000",
  anim="full_swing_mobile_loop",
  bank="fx_thatcher",
  bloom=20.0,
  build="fx_thatcher",
  group="fx_thatcher",
}
