-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="ground_indicator_beam_p1",
  anim="loop",
  bank="fx_item_drop",
  brightness=63.0,
  build="fx_item_pickup_untex",
  finaloffset=-1,
  glowcolor="0074FFFF",
  group="UI",
  looping=true,
  multcolor="4F75FF45",
  saturation=-61.0,
}
