-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_skill_yammo_focus",
  addcolor="FF1BFF00",
  anim="blunt_1",
  bank="fx_hits_focus",
  bloom=50.0,
  build="fx_hits_focus",
  glowcolor="03F2FFFF",
  group="hits_fx",
  multcolor="FF59FFFF",
  target_tint="FF640000",
}
