-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_skill_gourdo",
  addcolor="00FF0000",
  anim="hit_gourdo_",
  bank="fx_hits_player_skills",
  bloom=100.0,
  build="fx_hits_player_skills",
  glowcolor="00FF51FF",
  group="hits_fx",
  multcolor="BFFFBFFF",
  target_tint="FF640000",
  variations=3,
}
