-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_skill_yammo",
  addcolor="FF1BFF00",
  anim="blunt_",
  bank="hits_untex",
  bloom=50.0,
  build="fx_hits_all_untex",
  glowcolor="FDF600FF",
  group="hits_fx",
  multcolor="FF59FFFF",
  target_tint="FF640000",
  variations=3,
}
