-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_skill_yammo_crit",
  addcolor="FF1BFF00",
  anim="crit_blunt_",
  bank="fx_hits_crit",
  bloom=50.0,
  build="fx_hits_crit",
  glowcolor="D700FFFF",
  group="hits_fx",
  soundevent="Crit_blunt",
  target_tint="FF640000",
  variations=4,
}
