-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_acid",
  anim="1",
  autostop=true,
  bank="fx_hits_liquid",
  bloom=25.0,
  brightness=38.0,
  build="fx_hits_liquid",
  group="hits_fx",
  hue=57.0,
  saturation=33.0,
  soundevent="slowpoke_acid_splash",
  target_tint="29820000",
}
