-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_bomb_ground",
  anim="explode_grnd",
  bank="fx_trap_explosion",
  bloom=51.0,
  build="fx_trap_explosion",
  group="hits_fx",
  multcolor="FFFFFFD9",
  onground=true,
  sortorder=-1,
  target_tint="FF640000",
}
