-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_blunt_extra_focus",
  addcolor="0000FF00",
  anim="hit_player_",
  autostop=true,
  bank="fx_hits_jamball",
  bloom=50.0,
  brightness=1.0,
  build="fx_hits_jamball",
  glowcolor="0096FDFF",
  group="hits_fx",
  sound_max_count=1.0,
  soundevent="Hit_blunt_extra",
  target_tint="FF640000",
  variations=3,
}
