-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_skill_floracrane",
  addcolor="FF1BFF00",
  anim="blunt_",
  bank="hits_untex",
  bloom=50.0,
  build="fx_hits_all_untex",
  glowcolor="FDF600FF",
  group="hits_fx",
  multcolor="FF59FFFF",
  soundevent="Power_VolatileWeaponry_Impact_Counter",
  target_tint="FF640000",
  variations=3,
  window_frames=1.0,
}
