-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="hits_player_blunt_extra_crit",
  anim="crit_blunt_",
  autostop=true,
  bank="fx_hits_crit",
  bloom=100.0,
  build="fx_hits_crit",
  glowcolor="CF00FDFF",
  group="hits_fx",
  scalex=0.80000001192093,
  scaley=0.80000001192093,
  sound_max_count=1.0,
  soundevent="Crit_blunt",
  target_tint="FF640000",
  variations=4,
}
