-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="interactable_indicator",
  addcolor="12120F00",
  additive=true,
  anim="indicator",
  bank="aim_pointer_ground_indicator",
  bloom=17.0,
  build="aim_pointer_ground_indicator",
  finaloffset=-1,
  group="UI",
  looping=true,
  multcolor="2B36FF7D",
  randomstartframe=true,
  scalex=0.80000001192093,
  scaley=0.80000001192093,
  sortorder=1,
}
