-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="lightrays_spotlight_thatcher",
  addcolor="00BE1900",
  anim="idle_spotlight_straight",
  autostop=true,
  bank="fx_lightrays",
  bloom=42.0,
  brightness=-3.0,
  build="fx_lightrays",
  group="bombs_traps",
  lightoverride=100.0,
  looping=true,
  multcolor="FFFFFFA6",
  randomstartframe=true,
  saturation=100.0,
}
