-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="remove_decor_pointer_p4",
  additive=true,
  anim="remove_decor_pointer",
  bank="aim_pointer_ground_indicator",
  bloom=50.0,
  build="aim_pointer_ground_indicator",
  finaloffset=-1,
  glowcolor="6000FFFF",
  group="UI",
  looping=true,
  multcolor="4A4AFFD4",
  onground=true,
}
