-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="remove_decor_pointer_p1",
  additive=true,
  anim="remove_decor_pointer",
  bank="aim_pointer_ground_indicator",
  bloom=80.0,
  build="aim_pointer_ground_indicator",
  finaloffset=-1,
  glowcolor="0074FFFF",
  group="UI",
  looping=true,
  multcolor="2B36FFD4",
  onground=true,
}
