-- Generated by FxEditor and loaded by fx_autogen.lua
return {
  __displayName="skill_gourdo_heal_loop_swirl_back",
  anim="swirl_back",
  bank="fx_aquire_item_ui",
  bloom=50.0,
  build="fx_aquire_item_ui",
  glowcolor="00FF04FF",
  group="player_skills",
  layer="bg",
  multcolor="FFFFFFCC",
  noflip=true,
  sortorder=2,
}
