-- Generated by WorldEditor and loaded by world_autogen.lua
return {
  __displayName="town_plots_base_wide2",
  group="town",
  layout="town/town_plots_base_wide2",
  scene_gen_overrides={
    lighting={
      ambient="C9BBB6FF",
      clifflightweight=0.46200001239777,
      colorcube={ boss="town_cc", entrance="town_cc",},
      rimlightcolor="FFA36DFF",
      shadowSkew={ -100.0, 100.0, 0.5, 0.5,},
      shadowSquish={ -10.0, 10.0, 1.0, 1.0,},
    },
    sky={
      backgroundGradientCurve={
        boss={
          { 0, 0.93506491184235, 0.89049196243286, 0.5737898349762,},
          { 0.1010101010101, 0.90584415197372, 0.73950278759003, 0.52350735664368,},
          { 0.19489981785064, 0.62839192152023, 0.56878048181534, 0.76050418615341,},
          { 0.56137184115523, 0.21568627655506, 0.15686275064945, 0.38039216399193,},
        },
        entrance={
          { 0, 0.93506491184235, 0.89049196243286, 0.5737898349762,},
          { 0.1010101010101, 0.90584415197372, 0.73950278759003, 0.52350735664368,},
          { 0.19489981785064, 0.62839192152023, 0.56878048181534, 0.76050418615341,},
          { 0.56137184115523, 0.21568627655506, 0.15686275064945, 0.38039216399193,},
        },
      },
      prop_fade_color="372861FF",
    },
  },
  town=true,
}
