-- Generated by CineEditor and loaded by cine_autogen.lua
return {
  __displayName="cine_town_spawn_victory",
  pause_role_sg={  },
  scene_duration=235.0,
  scene_init={  },
  subactors={  },
  timelines={
    cameradist={
      { 0, 1, { eventtype="cameradist", param={ cut=true, dist=22.0, duration=1,},},},
      {
        70,
        125,
        {
          eventtype="cameradist",
          param={
            curve={
              0.0,
              0,
              0.14285714924335,
              0.049515571445227,
              0.28571429848671,
              0.1882551163435,
              0.4285714328289,
              0.38873952627182,
              0.57142859697342,
              0.61126053333282,
              0.71428573131561,
              0.81174492835999,
              0.85714286565781,
              0.95048445463181,
              1.0,
              1.0,
            },
            duration=55,
          },
        },
      },
    },
    camerapitch={
      { 0, 1, { eventtype="camerapitch", param={ cut=true, duration=1, pitch=16.0,},},},
      {
        82,
        125,
        {
          eventtype="camerapitch",
          param={
            curve={
              0.0,
              0,
              0.14285714924335,
              0.040816329419613,
              0.28571429848671,
              0.16326531767845,
              0.4285714328289,
              0.36734694242477,
              0.57142859697342,
              0.63265311717987,
              0.71428573131561,
              0.83673471212387,
              0.85714286565781,
              0.95918369293213,
              1.0,
              1.0,
            },
            duration=43,
            pitch=23.578178405762,
          },
        },
      },
    },
    cameratargetbegin={
      {
        0,
        1,
        {
          eventtype="cameratargetbegin",
          param={ cut=true, duration=1,},
          target_role="players",
        },
      },
    },
    cameratargetend={
      {
        70,
        125,
        {
          apply_to_all_players=false,
          eventtype="cameratargetend",
          param={
            curve={
              0.0,
              0,
              0.14285714924335,
              0.040816329419613,
              0.28571429848671,
              0.16326531767845,
              0.4285714328289,
              0.36734694242477,
              0.57142859697342,
              0.63265311717987,
              0.71428573131561,
              0.83673471212387,
              0.85714286565781,
              0.95918369293213,
              1.0,
              1.0,
            },
            duration=55,
          },
          target_role="players",
        },
      },
    },
    disableplayinput={ { 0, 235.0, { eventtype="disableplayinput", param={  },},},},
    fade={
      {
        0,
        50,
        { eventtype="fade", param={ duration=50, fade_in=true, fade_type="black",},},
      },
    },
    gotostate={
      {
        51,
        66,
        {
          apply_to_all_players=true,
          eventtype="gotostate",
          param={ duration=15, statename="cheer",},
          target_role="players",
        },
      },
    },
    letterbox={ { 0, 82.0, { eventtype="letterbox", param={ duration=82,},},},},
    musicstart={ { 235, 235.0, { eventtype="musicstart", is_unedited=true, param={  },},},},
    playsound={
      {
        49,
        235.0,
        {
          eventtype="playsound",
          param={ sound_max_count=1.0, soundevent="Mus_Quest_BossFanfare_Stinger",},
        },
      },
    },
    uihidehud={ { 0, 93, { eventtype="uihidehud", param={ duration=93,},},},},
  },
}
