-- Generated by CineEditor and loaded by cine_autogen.lua
return {
  __displayName="cine_thatcher_intro",
  leadprefab="thatcher",
  pause_role_sg={ lead={ resumestate="idle",},},
  scene_duration=250.0,
  scene_init={ pos={ x=0.0, y=0, z=20.0,},},
  subactors={
    {
      assigned_at_runtime=false,
      end_pos={ pos={ x=-8.0, y=0, z=25.89999961853,},},
      face_left=false,
      kill_on_end=false,
      label="acid_geyser_LEFT",
      prefabname="thatcher_acid_geyser_left",
      show_on_spawn=true,
      start_pos={ pos={ x=-8.0, y=0, z=5.9,},},
    },
    {
      assigned_at_runtime=false,
      end_pos={ pos={ x=7.6799998283386, y=0, z=25.569999694824,},},
      face_left=false,
      kill_on_end=false,
      label="acidgeyser_RIGHT",
      prefabname="thatcher_acid_geyser_right",
      show_on_spawn=true,
      start_pos={ pos={ x=7.68, y=0, z=5.57,},},
    },
  },
  timelines={
    cameratargetoverride={
      {
        0,
        172,
        {
          eventtype="cameratargetoverride",
          param={ cut=true, dist=40.0, duration=172, offset={ x=0, y=0, z=10,},},
          target_role="lead",
        },
      },
      {
        172,
        224,
        {
          eventtype="cameratargetoverride",
          param={ dist=40.0, duration=52,},
          target_role="lead",
        },
      },
    },
    disableplayinput={ { 0, 223, { eventtype="disableplayinput", param={ duration=223,},},},},
    facing={
      {
        0,
        224,
        { eventtype="facing", param={ duration=224, facing="left",}, target_role="lead",},
      },
    },
    gotostate={
      {
        0,
        156,
        {
          eventtype="gotostate",
          param={ duration=156, statename="introduction",},
          target_role="lead",
        },
      },
    },
    letterbox={ { 0, 224, { eventtype="letterbox", param={ duration=224,},},},},
    musicbossstart={
      {
        244,
        250.0,
        {
          eventtype="musicbossstart",
          param={ persistent_key="boss_music", soundevent="Mus_Thatcher_LP",},
          target_role="lead",
        },
      },
    },
    playsound={
      {
        0,
        7,
        {
          eventtype="playsound",
          param={ duration=7, soundevent="sting_miniboss_intro",},
          target_role="lead",
        },
      },
      {
        1,
        5,
        {
          eventtype="playsound",
          param={ autostop=true, duration=4, soundevent="Mus_Thatcher_Intro",},
        },
      },
      {
        7,
        238,
        {
          eventtype="playsound",
          param={
            autostop=true,
            duration=231,
            name="Snapshot_BossIntro_LP",
            soundevent="Snapshot_BossIntro_LP",
            stopatexitstate=true,
          },
          target_role="lead",
        },
      },
    },
    setvisible={
      {
        0,
        1,
        { eventtype="setvisible", param={ duration=1, show=false,}, target_role="lead",},
      },
      {
        1,
        2,
        { eventtype="setvisible", param={ duration=1, show=true,}, target_role="lead",},
      },
    },
    shakecamera={
      {
        192,
        215,
        {
          eventtype="shakecamera",
          param={ duration=23, mode="FULL", scale=0.30000001192093, speed=0.026000000536442,},
        },
      },
      {
        215,
        239.0,
        {
          eventtype="shakecamera",
          param={ duration=24, mode="FULL", scale=0.2509999871254,},
        },
      },
    },
    showtext={
      {
        27,
        85,
        {
          eventtype="showtext",
          param={
            duration=58,
            monster_language_id="thatcher",
            offset_y=1000.0,
            textID="THATCHER_INTRO_1",
            use_monster_language=true,
          },
          target_role="lead",
        },
      },
      {
        87,
        145,
        {
          eventtype="showtext",
          param={
            duration=58,
            monster_language_id="thatcher",
            offset_y=1000.0,
            textID="THATCHER_INTRO_2",
            use_monster_language=true,
          },
          target_role="lead",
        },
      },
      {
        196,
        230,
        {
          eventtype="showtext",
          param={
            duration=34,
            monster_language_id="thatcher",
            offset_y=700.0,
            textID="THATCHER_INTRO_3",
            use_monster_language=true,
          },
          target_role="lead",
        },
      },
    },
    stopsound={
      {
        194,
        201,
        {
          eventtype="stopsound",
          param={ duration=7, name="Snapshot_BossIntro_LP",},
          target_role="lead",
        },
      },
    },
    titlecard={
      {
        41,
        97,
        {
          eventtype="titlecard",
          param={ duration=56, titlekey="thatcher",},
          target_role="lead",
        },
      },
    },
    uihidehud={ { 0, 224, { eventtype="uihidehud", param={ duration=224,},},},},
  },
  use_lead_actor_pos=true,
}
