-- Generated by CineEditor and loaded by cine_autogen.lua
return {
  __displayName="cine_dgn_pickup_abandon",
  pause_role_sg={  },
  scene_duration=100.0,
  scene_init={  },
  subactors={  },
  timelines={
    allsoundstop={ { 100, 100, { eventtype="allsoundstop", is_unedited=true, param={  },},},},
    cameradist={
      {
        0,
        19,
        {
          eventtype="cameradist",
          param={
            curve={
              0.0,
              0,
              0.14285714924335,
              0.26530614495277,
              0.28571429848671,
              0.48979592323303,
              0.4285714328289,
              0.6734693646431,
              0.57142859697342,
              0.81632655858994,
              0.71428573131561,
              0.91836738586426,
              0.85714286565781,
              0.97959184646606,
              1.0,
              1.0,
            },
            dist=22.0,
            duration=19,
          },
        },
      },
    },
    camerapitch={
      {
        0,
        19,
        {
          eventtype="camerapitch",
          param={
            curve={
              0.0,
              0,
              0.14285714924335,
              0.26530614495277,
              0.28571429848671,
              0.48979592323303,
              0.4285714328289,
              0.6734693646431,
              0.57142859697342,
              0.81632655858994,
              0.71428573131561,
              0.91836738586426,
              0.85714286565781,
              0.97959184646606,
              1.0,
              1.0,
            },
            duration=19,
            pitch=16.0,
          },
        },
      },
    },
    cameratargetbegin={
      {
        0,
        1,
        {
          eventtype="cameratargetbegin",
          param={ cut=true, duration=1,},
          target_role="players",
        },
      },
    },
    disableplayinput={ { 0, 100, { eventtype="disableplayinput", param={  },},},},
    fade={ { 70, 100, { eventtype="fade", param={ duration=30, fade_in=false,},},},},
    letterbox={ { 0, 100, { eventtype="letterbox", param={  },},},},
    playsound={
      {
        0,
        9,
        { eventtype="playsound", param={ duration=9, soundevent="flying_machine",},},
      },
      {
        2,
        20,
        {
          eventtype="playsound",
          param={
            autostop=true,
            duration=18,
            name="ratchet",
            soundevent="flying_machine_Ratchet_LP",
            stopatexitstate=true,
          },
        },
      },
      {
        25,
        29,
        {
          eventtype="playsound",
          param={ autostop=true, duration=4, soundevent="flying_machine_claw_open",},
        },
      },
      {
        44,
        60,
        {
          eventtype="playsound",
          param={
            autostop=true,
            duration=16,
            name="ratchet",
            soundevent="flying_machine_Ratchet_LP",
            stopatexitstate=true,
            volume=63.0,
          },
        },
      },
    },
    pushanim={
      {
        7,
        53,
        {
          apply_to_all_players=true,
          eventtype="pushanim",
          param={ anim="claw_abandon_pickup", duration=46, interrupt=true, max_random_delay=10.0,},
          target_role="players",
        },
      },
    },
    setvisible={
      {
        0,
        13,
        {
          eventtype="setvisible",
          param={ duration=13, show=true,},
          target_role="players",
        },
      },
      {
        69,
        80,
        {
          eventtype="setvisible",
          param={ duration=11, show=false,},
          target_role="players",
        },
      },
    },
    stopsound={ { 23, 28, { eventtype="stopsound", param={ duration=5, name="ratchet",},},},},
    uihidehud={ { 0, 100, { eventtype="uihidehud", param={  },},},},
  },
}
