-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_player_common_skills",
  anim_events={
    player_bank_skills_miniboss={
      skill_flora_dive={
        events={
          { frame=0, name="vfx-skill_flora_dive",},
          { frame=3, name="vfx-skill_flora_dive_impact",},
        },
      },
      skill_flora_dive_hold={ events={ { frame=0, name="vfx-skill_flora_dive_hold",},},},
      skill_flora_dive_pre={ events={ { frame=3, name="vfx-skill_flora_dive_pre",},},},
      skill_gourdo_heal_loop={ events={ { frame=0, name="vfx-skill_gourdo_heal_loop",},},},
      skill_gourdo_heal_loop_pre={ events={ { frame=0, name="vfx-skill_gourdo_heal_loop_pre",},},},
      skill_gourdo_heal_pre={ events={ { frame=11, name="vfx-skill_gourdo_heal_pre",},},},
      skill_gourdo_heal_pst={ events={ { frame=1, name="vfx-skill_gourdo_heal_pst",},},},
      skill_groak_vacuum={ events={ { frame=0, name="vfx-skill_groak_vacuum",},},},
      skill_groak_vacuum_pre={ events={ { frame=0, name="vfx-skill_groak_vacuum_pre",},},},
      skill_groak_vacuum_pst={ events={ { frame=0, name="vfx-skill_groak_vacuum_pst",},},},
    },
  },
  prefab={ { prefab="player_side",},},
}
