-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_swarmy",
  anim_events={
    swarmy_bank={
      acid_burst2={ events={ { frame=14, name="vfx-acid_burst",},},},
      acid_dash={
        events={ { frame=17, name="vfx-acid_dash",}, { frame=1, name="vfx-idle_test",},},
      },
      uppercut={
        events={
          { frame=13, name="vfx-swarmy_uppercut",},
          { frame=34, name="vfx-uppercut_land",},
        },
      },
    },
  },
  prefab={ { prefab="swarmy",},},
}
