-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_totolili_projectile",
  anim_events={
    totolili_bank={ lily_hat_spin_loop={ events={ { frame=0, name="vfx-lily_hat_spin_loop",},},},},
  },
  prefab={ { prefab="totolili_projectile",},},
}
