-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_totolili",
  anim_events={
    totolili_bank={
      lily_toss={ events={ { frame=11, name="vfx-lily_toss",},},},
      lily_toss_spin_pst={ events={ { frame=16, name="vfx-lily_toss_spin_pst",},},},
    },
  },
  prefab={ { prefab="totolili",},},
}
