-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="fx_woworm",
  anim_events={
    woworm_bank={
      puke={ events={ { frame=4, name="vfx-puke",},},},
      shell_slam={ events={ { frame=24, name="vfx-shellslam_ring",},},},
    },
  },
  prefab={ { prefab="woworm",},},
}
