-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="shake_gourdo",
  anim_events={
    gourdo_bank={
      butt_slam={ events={ { frame=30, name="shake-butt_slam",},},},
      elite_butt_slam_middle_loop={ events={ { frame=36, name="shake-butt_slam_elite",},},},
      elite_butt_slam_start={ events={ { frame=23, name="shake-butt_slam_elite",},},},
      knockdown_pre={ events={ { frame=7, name="shake-knockdown",},},},
      spawn2_pst={ events={ { frame=0, name="shake-spawn",},},},
      spawn3_pst={ events={ { frame=0, name="shake-knockdown",},},},
    },
  },
  group="screenshakes",
  prefab={ { prefab="gourdo",}, { prefab="gourdo_elite",},},
}
