-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="shake_floracrane",
  anim_events={
    floracrane_bank={
      dive={ events={ { frame=30, name="shake-dive",},},},
      hop_above={ events={ { frame=18, name="shake-hop",},},},
      hop_below={ events={ { frame=19, name="shake-hop",},},},
      hop_forward={ events={ { frame=19, name="shake-hop",},},},
    },
  },
  group="screenshakes",
  prefab={ { prefab="floracrane_elite",}, { prefab="floracrane",},},
}
