-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="shake_yammo",
  anim_events={
    yammo_bank={
      elite_heavy_slam={ events={ { frame=12, name="shake-elite_heavy_slam",},},},
      elite_heavy_slam_run_loop={ events={ { frame=6, name="shake-run",}, { frame=28, name="shake-run",},},},
      elite_swing_run_loop={ events={ { frame=9, name="shake-run",}, { frame=27, name="shake-run",},},},
      heavy_slam={ events={ { frame=12, name="shake-heavy_slam",},},},
      knockdown_pre={ events={ { frame=11, name="shake-knockdown",},},},
      spawn_jump_pst={ events={ { frame=1, name="shake-spawn_jump",},},},
      walk_loop={ events={ { frame=11, name="shake-step",}, { frame=40, name="shake-step",},},},
      walk_pst={ events={ { frame=1, name="shake-step",},},},
    },
  },
  group="screenshakes",
  prefab={ { prefab="yammo",}, { prefab="yammo_elite",},},
}
