-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_woworm_shell",
  anim_events={
    woworm_shell_bank={
      death={ events={ { frame=0, name="sfx-death",}, { frame=0, name="sfx-hit",},},},
      flinch_pst={ events={ { frame=1, name="sfx-foley",},},},
      hit_back_hold={ events={ { frame=0, name="sfx-hit",},},},
      hit_back_pst={ events={ { frame=1, name="sfx-foley",},},},
      hit_hold={ events={ { frame=0, name="sfx-hit",},},},
      hit_pst={ events={ { frame=2, name="sfx-foley",},},},
      knockdown_getup={ events={ { frame=1, name="sfx-foley",},},},
      knockdown_pre={ events={ { frame=13, name="sfx-hit",},},},
      spawn={ events={ { frame=3, name="sfx-foley",}, { frame=7, name="sfx-foley",},},},
    },
  },
  prefab={ { prefab="woworm_shell",},},
}
