-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_town_energy_well",
  anim_events={
    town_grid_heart={
      excited={
        done=true,
        events={
          { frame=9, name="sfx-bounce", postfix="_4",},
          { frame=17, name="sfx-bounce", postfix="_4",},
          { frame=25, name="sfx-bounce", postfix="_4",},
          { frame=33, name="sfx-bounce", postfix="_4",},
          { frame=41, name="sfx-bounce", postfix="_4",},
          { frame=49, name="sfx-bounce", postfix="_4",},
          { frame=1, name="sfx-bounce", postfix="_4",},
        },
      },
      idle={
        events={
          { frame=1, name="sfx-shake", postfix="_4",},
          { frame=19, name="sfx-rattle", postfix="_4",},
          { frame=70, name="sfx-rattle", postfix="_4",},
          { frame=72, name="sfx-tick_forward_fast", postfix="_4",},
          { frame=102, name="sfx-pulse", postfix="_4",},
          { frame=117, name="sfx-rattle", postfix="_4",},
          { frame=169, name="sfx-rattle", postfix="_4",},
          { frame=171, name="sfx-tick_forward_fast", postfix="_4",},
          { frame=190, name="sfx-tick_forward_fast", postfix="_4",},
          { frame=90, name="sfx-tick_forward_fast", postfix="_4",},
        },
      },
    },
  },
  prefab={ { baseanim="4", prefab="town_energy_well",}, {  },},
}
