-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_cabbagerolls",
  anim_events={
    cabbageroll4_bank={
      body_slam_hold={ done=true, events={ { frame=1, name="sfx-hold",},},},
      bodyslam={
        done=true,
        events={
          { frame=1, name="sfx-whoosh",},
          { frame=21, name="sfx-groundslam",},
          { frame=19, name="sfx-groundslam_quiet",},
          { frame=13, name="sfx-vo",},
          { frame=15, name="sfx-vo",},
          { frame=14, name="sfx-vo_pitched",},
        },
      },
      bodyslam_pre={ done=true,},
      cabbageroll3_behavior1={ done=true, events={ { frame=6, name="sfx-behavior1",},},},
      cabbageroll3_combine3={
        done=true,
        events={
          { frame=1, name="sfx-bodyfall",},
          { frame=10, name="sfx-vo",},
          { frame=16, name="sfx-footstep",},
          { frame=17, name="sfx-bodyfall",},
          { frame=18, name="sfx-footstep",},
        },
      },
      cabbageroll3_hit_back_hold={ done=true, events={ { frame=0, name="sfx-hit",},},},
      cabbageroll3_hit_back_pst={ done=true,},
      cabbageroll3_hit_hold={ events={ { frame=0, name="sfx-hit",},},},
      cabbageroll3_hit_pst={ done=true, events={ { frame=1, name="sfx-vo_pitched",},},},
      cabbageroll3_knockdown={ done=true, events={ { frame=1, name="sfx-knock",},},},
      cabbageroll3_walk_loop={
        done=true,
        events={ { frame=4, name="sfx-footstep",}, { frame=12, name="sfx-footstep",},},
      },
      cabbageroll3_walk_pre={ done=true,},
      cabbageroll3_walk_pst={ done=true, events={ { frame=5, name="sfx-footstep",},},},
      catapult={ done=true, events={ { frame=1, name="sfx-throw",},},},
      catapult_hold={ done=true,},
      catapult_pre={ done=true, events={ { frame=1, name="sfx-hold",},},},
      flinch_hold={ done=true,},
      flinch_pst={
        done=true,
        events={
          { frame=18, name="sfx-footstep",},
          { frame=20, name="sfx-footstep",},
          { frame=0, name="sfx-knock",},
        },
      },
      smash={
        done=true,
        events={
          { frame=9, name="sfx-groundslam",},
          { frame=9, name="sfx-slap",},
          { frame=21, name="sfx-groundslam",},
          { frame=21, name="sfx-slap",},
          { frame=36, name="sfx-vo_pitched",},
        },
      },
      smash_hold={ done=true, events={ { frame=1, name="sfx-hold",},},},
      smash_pre={ done=true, events={ { frame=2, name="sfx-whoosh",},},},
      spawn3={
        done=true,
        events={
          { frame=1, name="sfx-whoosh",},
          { frame=3, name="sfx-whoosh",},
          { frame=6, name="sfx-whoosh",},
          { frame=16, name="sfx-groundslam_quiet",},
          { frame=20, name="sfx-groundslam_quiet",},
          { frame=29, name="sfx-vo_pitched",},
          { frame=46, name="sfx-ground_slam",},
          { frame=46, name="sfx-slap",},
          { frame=46, name="sfx-vo",},
          { frame=28, name="sfx-groundslam",},
        },
      },
    },
  },
  prefab={ { prefab="cabbagerolls",},},
}
