-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_thatcherswamp_path",
  anim_events={
    thatforest_gate={
      open={
        done=true,
        events={
          { frame=1, name="sfx-open_magic", postfix="_empty",},
          { frame=11, name="sfx-open_moan", postfix="_empty",},
          { frame=9, name="sfx-open", postfix="_empty",},
        },
      },
    },
  },
  prefab={
    { baseanim="empty", prefab="thatforest_gate_n",},
    { baseanim="empty", prefab="thatforest_gate_e",},
    { baseanim="empty", prefab="thatforest_gate_s",},
    { baseanim="empty", prefab="thatforest_gate_w",},
  },
}
