-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_corestone_many",
  anim_events={
    power_drop_generic={
      idle={
        done=true,
        events={
          { frame=0, name="sfx-rattle", postfix="_1",},
          { frame=15, name="sfx-rattle", postfix="_1",},
          { frame=45, name="sfx-rattle", postfix="_1",},
          { frame=84, name="sfx-rattle", postfix="_1",},
          { frame=119, name="sfx-rattle", postfix="_1",},
        },
      },
      shatter={
        done=true,
        events={
          { frame=1, name="sfx-rumble", postfix="_1",},
          { frame=10, name="sfx-shatter_crystal", postfix="_1",},
          { frame=10, name="sfx-shatter_tail", postfix="_1",},
        },
      },
      spawn={
        done=true,
        events={
          { frame=1, name="sfx-energy", postfix="_1",},
          { frame=5, name="sfx-crystallize", postfix="_1",},
          { frame=34, name="sfx-ping", postfix="_1",},
        },
      },
    },
    soul_drop_konjur_soul_greater={
      shatter={
        done=true,
        events={
          { frame=10, name="sfx-shatter_crystal", postfix="_1",},
          { frame=10, name="sfx-shatter_tail", postfix="_1",},
          { frame=1, name="sfx-rumble", postfix="_1",},
        },
      },
      spawn={
        done=true,
        events={
          { frame=0, name="sfx-energy", postfix="_1",},
          { frame=5, name="sfx-crystallize", postfix="_1",},
        },
      },
    },
    soul_drop_konjur_soul_lesser={
      shatter={
        done=true,
        events={
          { frame=10, name="sfx-shatter_crystal", postfix="_1",},
          { frame=10, name="sfx-shatter_tail", postfix="_1",},
        },
      },
      spawn={ done=true, events={ { frame=1, name="sfx-energy", postfix="_1",},},},
    },
    soul_drop_konjur_soul_lesser_double={
      shatter={
        events={
          { frame=10, name="sfx-shatter_crystal", postfix="_1",},
          { frame=10, name="sfx-shatter_tail", postfix="_1",},
        },
      },
      spawn={ events={ { frame=0, name="sfx-sfx-energy", postfix="_1",},},},
    },
  },
  prefab={ { baseanim="1", prefab="soul_drop_konjur_soul_lesser_many",},},
}
