-- Generated by AnimTagger and loaded by animtag_autogen.lua
return {
  __displayName="sound_cabbagerolls2",
  anim_events={
	cabbageroll4_bank={
      cabbageroll2_behavior={
        done=true,
        events={
          { frame=20, name="sfx-footstep",},
          { frame=32, name="sfx-bodyfall",},
          { frame=32, name="sfx-footstep",},
          { frame=34, name="sfx-vo_pitched",},
        },
      },
      catapult_pst={
        done=true,
        events={ { frame=1, name="sfx-vo_pitched",}, { frame=9, name="sfx-footstep",},},
      },
      cabbageroll2_combine={
        done=true,
        events={ { frame=1, name="sfx-bodyfall",}, { frame=4, name="sfx-vo_pitched",},},
      },
      flinch_hold={ done=true, events={ { frame=1, name="sfx-knockdown",},},},
      flinch_pst={
        done=true,
        events={ { frame=1, name="sfx-vo_pitched",}, { frame=5, name="sfx-hit",},},
      },
      cabbageroll2_hit_back_hold={ done=true, events={ { frame=0, name="sfx-knockdown",},},},
      cabbageroll2_hit_back_pst={ done=true,},
      cabbageroll2_hit_hold={ done=true, events={ { frame=0, name="sfx-hit",},},},
      cabbageroll2_knockdown={ done=true, events={ { frame=1, name="sfx-knockdown",},},},
      slam={
        done=true,
        events={
          { frame=28, name="sfx-ground_hit",},
          { frame=48, name="sfx-bodyfall",},
          { frame=51, name="sfx-vo_pitched",},
          { frame=9, name="sfx-slam",},
          { frame=6, name="sfx-ground_hit",},
        },
      },
      slam_hold={ events={ { frame=1, name="sfx-hold",},},},
      slam_pre={ done=true, events={ { frame=1, name="sfx-vo",},},},
      spawn2={
        done=true,
        events={
          { frame=16, name="sfx-bodyfall",},
          { frame=21, name="sfx-bodyfall",},
          { frame=24, name="sfx-vo_pitched",},
          { frame=3, name="sfx-whoosh",},
          { frame=6, name="sfx-whoosh",},
          { frame=9, name="sfx-whoosh",},
          { frame=12, name="sfx-whoosh",},
          { frame=15, name="sfx-whoosh",},
          { frame=16, name="sfx-ground_hit",},
          { frame=21, name="sfx-ground_hit",},
        },
      },
      throw={
        done=true,
        events={ { frame=3, name="sfx-hit",}, { frame=1, name="sfx-throw",},},
      },
      throw_hold={ events={ { frame=1, name="sfx-hold",},},},
      turn_pre={ done=true,},
      turn_pre_cabbageroll2_walk_pre={ done=true,},
      turn_pst={ done=true,},
      turn_pst_cabbageroll2_walk_pre={ done=true,},
      cabbageroll2_walk_loop={
        done=true,
        events={ { frame=4, name="sfx-footstep",}, { frame=12, name="sfx-footstep",},},
      },
      cabbageroll2_walk_pre={ done=true,},
      cabbageroll2_walk_pst={ done=true,},
    },
  },
  prefab={ { prefab="cabbagerolls2",},},
}
